# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from linksoft_sdk.pb.apps.posto.bomba import bomba_pb2 as apps_dot_posto_dot_bomba_dot_bomba__pb2


class BombaServiceStub:
    """Serviço Bomba com operações CRUD
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/bomba.BombaService/Create',
                request_serializer=apps_dot_posto_dot_bomba_dot_bomba__pb2.CreateRequest.SerializeToString,
                response_deserializer=apps_dot_posto_dot_bomba_dot_bomba__pb2.CreateResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/bomba.BombaService/Update',
                request_serializer=apps_dot_posto_dot_bomba_dot_bomba__pb2.UpdateRequest.SerializeToString,
                response_deserializer=apps_dot_posto_dot_bomba_dot_bomba__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/bomba.BombaService/Delete',
                request_serializer=apps_dot_posto_dot_bomba_dot_bomba__pb2.DeleteRequest.SerializeToString,
                response_deserializer=apps_dot_posto_dot_bomba_dot_bomba__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/bomba.BombaService/Get',
                request_serializer=apps_dot_posto_dot_bomba_dot_bomba__pb2.GetRequest.SerializeToString,
                response_deserializer=apps_dot_posto_dot_bomba_dot_bomba__pb2.GetResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/bomba.BombaService/List',
                request_serializer=apps_dot_posto_dot_bomba_dot_bomba__pb2.ListRequest.SerializeToString,
                response_deserializer=apps_dot_posto_dot_bomba_dot_bomba__pb2.ListResponse.FromString,
                _registered_method=True)


class BombaServiceServicer:
    """Serviço Bomba com operações CRUD
    """

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BombaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=apps_dot_posto_dot_bomba_dot_bomba__pb2.CreateRequest.FromString,
                    response_serializer=apps_dot_posto_dot_bomba_dot_bomba__pb2.CreateResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=apps_dot_posto_dot_bomba_dot_bomba__pb2.UpdateRequest.FromString,
                    response_serializer=apps_dot_posto_dot_bomba_dot_bomba__pb2.UpdateResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=apps_dot_posto_dot_bomba_dot_bomba__pb2.DeleteRequest.FromString,
                    response_serializer=apps_dot_posto_dot_bomba_dot_bomba__pb2.DeleteResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=apps_dot_posto_dot_bomba_dot_bomba__pb2.GetRequest.FromString,
                    response_serializer=apps_dot_posto_dot_bomba_dot_bomba__pb2.GetResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=apps_dot_posto_dot_bomba_dot_bomba__pb2.ListRequest.FromString,
                    response_serializer=apps_dot_posto_dot_bomba_dot_bomba__pb2.ListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bomba.BombaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bomba.BombaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BombaService:
    """Serviço Bomba com operações CRUD
    """

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bomba.BombaService/Create',
            apps_dot_posto_dot_bomba_dot_bomba__pb2.CreateRequest.SerializeToString,
            apps_dot_posto_dot_bomba_dot_bomba__pb2.CreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bomba.BombaService/Update',
            apps_dot_posto_dot_bomba_dot_bomba__pb2.UpdateRequest.SerializeToString,
            apps_dot_posto_dot_bomba_dot_bomba__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bomba.BombaService/Delete',
            apps_dot_posto_dot_bomba_dot_bomba__pb2.DeleteRequest.SerializeToString,
            apps_dot_posto_dot_bomba_dot_bomba__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bomba.BombaService/Get',
            apps_dot_posto_dot_bomba_dot_bomba__pb2.GetRequest.SerializeToString,
            apps_dot_posto_dot_bomba_dot_bomba__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bomba.BombaService/List',
            apps_dot_posto_dot_bomba_dot_bomba__pb2.ListRequest.SerializeToString,
            apps_dot_posto_dot_bomba_dot_bomba__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
