// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: apps/dfe/anp/anp.proto

package anp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnpService_List_FullMethodName = "/anp.AnpService/List"
)

// AnpServiceClient is the client API for AnpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Lista fixa de códigos ANP (combustíveis e lubrificantes). Sem persistência.
type AnpServiceClient interface {
	List(ctx context.Context, in *ListAnpRequest, opts ...grpc.CallOption) (*ListAnpResponse, error)
}

type anpServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnpServiceClient(cc grpc.ClientConnInterface) AnpServiceClient {
	return &anpServiceClient{cc}
}

func (c *anpServiceClient) List(ctx context.Context, in *ListAnpRequest, opts ...grpc.CallOption) (*ListAnpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAnpResponse)
	err := c.cc.Invoke(ctx, AnpService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnpServiceServer is the server API for AnpService service.
// All implementations must embed UnimplementedAnpServiceServer
// for forward compatibility.
//
// Lista fixa de códigos ANP (combustíveis e lubrificantes). Sem persistência.
type AnpServiceServer interface {
	List(context.Context, *ListAnpRequest) (*ListAnpResponse, error)
	mustEmbedUnimplementedAnpServiceServer()
}

// UnimplementedAnpServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnpServiceServer struct{}

func (UnimplementedAnpServiceServer) List(context.Context, *ListAnpRequest) (*ListAnpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAnpServiceServer) mustEmbedUnimplementedAnpServiceServer() {}
func (UnimplementedAnpServiceServer) testEmbeddedByValue()                    {}

// UnsafeAnpServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnpServiceServer will
// result in compilation errors.
type UnsafeAnpServiceServer interface {
	mustEmbedUnimplementedAnpServiceServer()
}

func RegisterAnpServiceServer(s grpc.ServiceRegistrar, srv AnpServiceServer) {
	// If the following call panics, it indicates UnimplementedAnpServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnpService_ServiceDesc, srv)
}

func _AnpService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAnpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnpServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnpService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnpServiceServer).List(ctx, req.(*ListAnpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnpService_ServiceDesc is the grpc.ServiceDesc for AnpService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnpService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anp.AnpService",
	HandlerType: (*AnpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _AnpService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/dfe/anp/anp.proto",
}
