syntax = "proto3";

package cfop;

import "google/api/annotations.proto";

import "plugins/validate/validate.proto";

import "plugins/service/service.proto";

import "filter/filter.proto";

import "common/metadata/metadata.proto";

option go_package = "comps/pb/apps/dfe/cfop";

// Serviço Cfop com operações CRUD
service CfopService {
  rpc Create ( CreateCfopRequest ) returns ( CreateCfopResponse );

  rpc Update ( UpdateCfopRequest ) returns ( UpdateCfopResponse );

  rpc Delete ( DeleteCfopRequest ) returns ( DeleteCfopResponse );

  rpc Get ( GetCfopRequest ) returns ( GetCfopResponse );

  rpc List ( ListCfopRequest ) returns ( ListCfopResponse );

  // Métodos não-CRUD
  rpc FindByOperacao ( FindByOperacaoRequest ) returns ( FindByOperacaoResponse );

  rpc ImportaTabela ( ImportaTabelaRequest ) returns ( ImportaTabelaResponse );
}

// Dados do Cfop
message Cfop {
  string id = 1;

  string codigo = 3;

  string descricao = 4;

  string aplicacao = 5;

  string categoria = 6;

  string tipo_operacao = 7;

  bool fora_do_estado = 8;

  bool operacao_com_exterior = 9;

  bool valido_nfe = 10;

  bool valido_nfce = 11;

  bool valido_cte = 12;

  bool valido_cte_os = 13;

  bool valido_servico_comunicacao = 14;

  bool valido_retencao_icms_transporte = 15;

  bool valido_devolucao = 16;

  bool valido_retorno_mercadoria = 17;

  bool valido_transferencia = 18;

  bool valido_venda = 19;

  bool valido_anulacao = 20;

  bool valido_remessa = 21;

  bool valido_operacao_combustivel = 22;
}

// Request e Response para criação de Cfop
message CreateCfopRequest {
  Cfop cfop = 1;
}

message CreateCfopResponse {
  Cfop cfop = 1;
}

// Request e Response para atualização de Cfop
message UpdateCfopRequest {
  string id = 1; // ID da NFSe a ser atualizada

  Cfop cfop = 2;

  metadata.FieldMask update_mask = 3;
}

// Request e Response para atualização de Cfop
message UpdateCfopResponse {
  Cfop cfop = 1;
}

// Request e Response para exclusão de Cfop
message DeleteCfopRequest {
  string id = 1;

  bool hard = 2;
}

message DeleteCfopResponse {
  string id = 1;
}

// Request para obter um Cfop por ID
message GetCfopRequest {
  string id = 1;
}

// Request para obter um Cfop por ID
message GetCfopResponse {
  Cfop cfop = 1;
}

// Request e Response para listagem de Cfops
message ListCfopRequest {
  repeated string ids = 1;

  uint32 page_size = 2;

  string page_token = 3;

  Filter filter = 5;
}

message ListCfopResponse {
  repeated Cfop cfopList = 1;

  string next_page_token = 2;
}

// Request e Response para FindByOperacao
message FindByOperacaoRequest {
  string tipo_operacao = 1; // "ENTRADA" ou "SAIDA"

  string tipo_documento = 2; // "nfe", "nfce", "cte", "cteos"

  string natureza_operacao = 3;

  bool fora_estado = 4;
}

message FindByOperacaoResponse {
  message CfopValido {
    string codigo = 1;

    string descricao = 2;
  }

  repeated CfopValido cfop_list = 1;
}

// Request e Response para ImportaTabela
message ImportaTabelaRequest {
  string file_string = 1;
}

message ImportaTabelaResponse {
  string mensagem = 1;
}
