syntax = "proto3";

import "google/api/annotations.proto";

import "apps/vendas/pedido/pedido.proto";

package quotes;

option go_package = "comps/pb/apps/vendas/quotes";

service QuotesService {
  rpc Create ( pedido.CreatePedidoRequest ) returns ( pedido.CreatePedidoResponse );

  rpc Update ( pedido.UpdatePedidoRequest ) returns ( pedido.UpdatePedidoResponse );

  rpc SetAcompanhamento ( pedido.SetAcompanhamentoRequest ) returns ( pedido.SetAcompanhamentoResponse );

  rpc ReorderItems ( pedido.ReorderItemsRequest ) returns ( pedido.ReorderItemsResponse );

  rpc Export ( pedido.ExportOrdersRequest ) returns ( pedido.ExportOrdersResponse );

  rpc Delete ( pedido.DeletePedidoRequest ) returns ( pedido.DeletePedidoResponse );

  rpc Get ( pedido.GetPedidoRequest ) returns ( pedido.GetPedidoResponse );

  rpc List ( pedido.ListPedidoRequest ) returns ( pedido.ListPedidoResponse );

  rpc Print ( pedido.PrintPedidoRequest ) returns ( pedido.PrintPedidoResponse );

  rpc GenerateFromOrcamento ( pedido.GenerateFromOrcamentoRequest ) returns ( pedido.GenerateFromOrcamentoResponse );

  rpc Cancel ( pedido.CancelPedidoRequest ) returns ( pedido.CancelPedidoResponse );

  rpc Clone ( pedido.ClonePedidoRequest ) returns ( pedido.ClonePedidoResponse );

  rpc AddProduct ( pedido.AddProductRequest ) returns ( pedido.AddProductResponse );

  rpc UpdateProduct ( pedido.UpdateProductRequest ) returns ( pedido.UpdateProductResponse );

  rpc DeleteProduct ( pedido.DeleteProductRequest ) returns ( pedido.DeleteProductResponse );

  rpc AddService ( pedido.AddServiceRequest ) returns ( pedido.AddServiceResponse );

  rpc UpdateService ( pedido.UpdateServiceRequest ) returns ( pedido.UpdateServiceResponse );

  rpc DeleteService ( pedido.DeleteServiceRequest ) returns ( pedido.DeleteServiceResponse );

  rpc SendByEmail ( pedido.SendByEmailRequest ) returns ( pedido.SendByEmailResponse );

  rpc SendReminder ( pedido.SendReminderRequest ) returns ( pedido.SendReminderResponse );

  rpc AplicaTabelaPreco ( pedido.AplicaTabelaPrecoRequest ) returns ( pedido.AplicaTabelaPrecoResponse );

  rpc Report ( pedido.ReportRequest ) returns ( pedido.ReportResponse );

  rpc Import ( pedido.ImportRequest ) returns ( pedido.ImportResponse );

  rpc SincronizaPessoa ( pedido.SincronizaPessoaRequest ) returns ( pedido.SincronizaPessoaResponse );
}
