# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from linksoft_sdk.pb.apps.estoque.serial import serial_pb2 as apps_dot_estoque_dot_serial_dot_serial__pb2


class SerialServiceStub:
    """Serviço Serial com operações CRUD
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/serial.SerialService/Create',
                request_serializer=apps_dot_estoque_dot_serial_dot_serial__pb2.CreateSerialRequest.SerializeToString,
                response_deserializer=apps_dot_estoque_dot_serial_dot_serial__pb2.CreateSerialResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/serial.SerialService/Update',
                request_serializer=apps_dot_estoque_dot_serial_dot_serial__pb2.UpdateSerialRequest.SerializeToString,
                response_deserializer=apps_dot_estoque_dot_serial_dot_serial__pb2.UpdateSerialResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/serial.SerialService/Delete',
                request_serializer=apps_dot_estoque_dot_serial_dot_serial__pb2.DeleteSerialRequest.SerializeToString,
                response_deserializer=apps_dot_estoque_dot_serial_dot_serial__pb2.DeleteSerialResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/serial.SerialService/Get',
                request_serializer=apps_dot_estoque_dot_serial_dot_serial__pb2.GetSerialRequest.SerializeToString,
                response_deserializer=apps_dot_estoque_dot_serial_dot_serial__pb2.GetSerialResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/serial.SerialService/List',
                request_serializer=apps_dot_estoque_dot_serial_dot_serial__pb2.ListSerialRequest.SerializeToString,
                response_deserializer=apps_dot_estoque_dot_serial_dot_serial__pb2.ListSerialResponse.FromString,
                _registered_method=True)
        self.Report = channel.unary_unary(
                '/serial.SerialService/Report',
                request_serializer=apps_dot_estoque_dot_serial_dot_serial__pb2.ReportRequest.SerializeToString,
                response_deserializer=apps_dot_estoque_dot_serial_dot_serial__pb2.ReportResponse.FromString,
                _registered_method=True)


class SerialServiceServicer:
    """Serviço Serial com operações CRUD
    """

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Report(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SerialServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=apps_dot_estoque_dot_serial_dot_serial__pb2.CreateSerialRequest.FromString,
                    response_serializer=apps_dot_estoque_dot_serial_dot_serial__pb2.CreateSerialResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=apps_dot_estoque_dot_serial_dot_serial__pb2.UpdateSerialRequest.FromString,
                    response_serializer=apps_dot_estoque_dot_serial_dot_serial__pb2.UpdateSerialResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=apps_dot_estoque_dot_serial_dot_serial__pb2.DeleteSerialRequest.FromString,
                    response_serializer=apps_dot_estoque_dot_serial_dot_serial__pb2.DeleteSerialResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=apps_dot_estoque_dot_serial_dot_serial__pb2.GetSerialRequest.FromString,
                    response_serializer=apps_dot_estoque_dot_serial_dot_serial__pb2.GetSerialResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=apps_dot_estoque_dot_serial_dot_serial__pb2.ListSerialRequest.FromString,
                    response_serializer=apps_dot_estoque_dot_serial_dot_serial__pb2.ListSerialResponse.SerializeToString,
            ),
            'Report': grpc.unary_unary_rpc_method_handler(
                    servicer.Report,
                    request_deserializer=apps_dot_estoque_dot_serial_dot_serial__pb2.ReportRequest.FromString,
                    response_serializer=apps_dot_estoque_dot_serial_dot_serial__pb2.ReportResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'serial.SerialService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('serial.SerialService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SerialService:
    """Serviço Serial com operações CRUD
    """

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/serial.SerialService/Create',
            apps_dot_estoque_dot_serial_dot_serial__pb2.CreateSerialRequest.SerializeToString,
            apps_dot_estoque_dot_serial_dot_serial__pb2.CreateSerialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/serial.SerialService/Update',
            apps_dot_estoque_dot_serial_dot_serial__pb2.UpdateSerialRequest.SerializeToString,
            apps_dot_estoque_dot_serial_dot_serial__pb2.UpdateSerialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/serial.SerialService/Delete',
            apps_dot_estoque_dot_serial_dot_serial__pb2.DeleteSerialRequest.SerializeToString,
            apps_dot_estoque_dot_serial_dot_serial__pb2.DeleteSerialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/serial.SerialService/Get',
            apps_dot_estoque_dot_serial_dot_serial__pb2.GetSerialRequest.SerializeToString,
            apps_dot_estoque_dot_serial_dot_serial__pb2.GetSerialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/serial.SerialService/List',
            apps_dot_estoque_dot_serial_dot_serial__pb2.ListSerialRequest.SerializeToString,
            apps_dot_estoque_dot_serial_dot_serial__pb2.ListSerialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Report(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/serial.SerialService/Report',
            apps_dot_estoque_dot_serial_dot_serial__pb2.ReportRequest.SerializeToString,
            apps_dot_estoque_dot_serial_dot_serial__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
