syntax = "proto3";

package cce;

import "google/api/annotations.proto";

import "plugins/validate/validate.proto";

import "plugins/service/service.proto";

import "filter/filter.proto";

import "common/metadata/metadata.proto";

import "apps/report/report.proto";

import "google/protobuf/timestamp.proto";

option go_package = "comps/pb/apps/dfe/cce";

// Serviço Cce com operações CRUD
service CceService {
  rpc Create ( CreateCceRequest ) returns ( CreateCceResponse );

  rpc Update ( UpdateCceRequest ) returns ( UpdateCceResponse );

  rpc Delete ( DeleteCceRequest ) returns ( DeleteCceResponse );

  rpc Get ( GetCceRequest ) returns ( GetCceResponse );

  rpc List ( ListCceRequest ) returns ( ListCceResponse );

  // Envia uma CC-e para autorização
  rpc Envia ( GetCceRequest ) returns ( GetCceResponse );

  // Envia o PDF da CC-e por email
  rpc EnviaPdfEmail ( EnviaPdfEmailRequest ) returns ( EnviaPdfEmailResponse );

  // Imprime a CC-e
  rpc Imprimir ( ImprimirCceRequest ) returns ( ImprimirCceResponse );
}

// Dados do Cce
message Cce {
  google.protobuf.Timestamp createdAt = 1; // Data de criação

  google.protobuf.Timestamp updatedAt = 2; // Data de atualização

  string userId = 3; // ID do usuário que realizou a ação

  string userName = 4; // Nome do usuário que realizou a ação

  string id = 5;

  string chave = 6;

  string correcao = 7;

  string ambiente = 8;

  string situacao = 9;

  string protocolo = 10;

  int32 sequencia = 11;

  string xmlAutorizacao = 12;

  google.protobuf.Timestamp dataHoraAutorizacao = 13;

  repeated Rejeicao rejeicoes = 14;
}

message Rejeicao {
  string id = 1;

  google.protobuf.Timestamp dataHora = 2;

  google.protobuf.Timestamp dataHoraSituacaoDoc = 3;

  string cstat = 4;

  string mensagem = 5;
}

// Request e Response para criação de Cce
message CreateCceRequest {
  Cce cce = 1;
}

message CreateCceResponse {
  Cce cce = 1;
}

// Request e Response para atualização de Cce
message UpdateCceRequest {
  string id = 1; // ID da NFSe a ser atualizada

  Cce cce = 2;

  metadata.FieldMask update_mask = 3;
}

// Request e Response para atualização de Cce
message UpdateCceResponse {
  Cce cce = 1;
}

// Request e Response para exclusão de Cce
message DeleteCceRequest {
  string id = 1;

  bool hard = 2;
}

message DeleteCceResponse {
  string id = 1;
}

// Request para obter um Cce por ID
message GetCceRequest {
  string id = 1;
}

// Request para obter um Cce por ID
message GetCceResponse {
  Cce cce = 1;
}

// Request e Response para listagem de Cces
message ListCceRequest {
  repeated string ids = 1;

  uint32 page_size = 2;

  string page_token = 3;

  Filter filter = 5;

  google.protobuf.Timestamp createdAtGte = 6;

  google.protobuf.Timestamp createdAtLte = 7;

  string situacao = 8;
}

message ListCceResponse {
  repeated Cce cceList = 1;

  string next_page_token = 2;
}

// Request para enviar PDF da CC-e por email
message EnviaPdfEmailRequest {
  string id = 1; // ID da CC-e

  string email = 2; // Email para envio
}

// Resposta ao enviar PDF da CC-e por email
message EnviaPdfEmailResponse {
  bool success = 1;
}

// Request para imprimir a CC-e
message ImprimirCceRequest {
  string id = 1; // ID da CC-e
}

// Resposta de impressão da CC-e
message ImprimirCceResponse {
  report.Response response = 1;
}
