# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from linksoft_sdk.pb.apps.report import report_pb2 as apps_dot_report_dot_report__pb2


class ReportServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/report.ReportService/Create',
                request_serializer=apps_dot_report_dot_report__pb2.CreateReportRequest.SerializeToString,
                response_deserializer=apps_dot_report_dot_report__pb2.CreateReportResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/report.ReportService/Update',
                request_serializer=apps_dot_report_dot_report__pb2.UpdateReportRequest.SerializeToString,
                response_deserializer=apps_dot_report_dot_report__pb2.UpdateReportResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/report.ReportService/Delete',
                request_serializer=apps_dot_report_dot_report__pb2.DeleteReportRequest.SerializeToString,
                response_deserializer=apps_dot_report_dot_report__pb2.DeleteReportResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/report.ReportService/List',
                request_serializer=apps_dot_report_dot_report__pb2.ListReportRequest.SerializeToString,
                response_deserializer=apps_dot_report_dot_report__pb2.ListReportResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/report.ReportService/Get',
                request_serializer=apps_dot_report_dot_report__pb2.GetReportRequest.SerializeToString,
                response_deserializer=apps_dot_report_dot_report__pb2.GetReportResponse.FromString,
                _registered_method=True)
        self.GenerateReport = channel.unary_unary(
                '/report.ReportService/GenerateReport',
                request_serializer=apps_dot_report_dot_report__pb2.GenerateReportRequest.SerializeToString,
                response_deserializer=apps_dot_report_dot_report__pb2.GenerateReportResponse.FromString,
                _registered_method=True)
        self.SendByEmail = channel.unary_unary(
                '/report.ReportService/SendByEmail',
                request_serializer=apps_dot_report_dot_report__pb2.SendByEmailRequest.SerializeToString,
                response_deserializer=apps_dot_report_dot_report__pb2.SendByEmailResponse.FromString,
                _registered_method=True)
        self.SetDefaultReport = channel.unary_unary(
                '/report.ReportService/SetDefaultReport',
                request_serializer=apps_dot_report_dot_report__pb2.SetDefaultReportRequest.SerializeToString,
                response_deserializer=apps_dot_report_dot_report__pb2.SetDefaultReportResponse.FromString,
                _registered_method=True)


class ReportServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateReport(self, request, context):
        """Gera um relatorio com saida para varios formatos
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendByEmail(self, request, context):
        """Envia um relatório por email
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDefaultReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReportServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=apps_dot_report_dot_report__pb2.CreateReportRequest.FromString,
                    response_serializer=apps_dot_report_dot_report__pb2.CreateReportResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=apps_dot_report_dot_report__pb2.UpdateReportRequest.FromString,
                    response_serializer=apps_dot_report_dot_report__pb2.UpdateReportResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=apps_dot_report_dot_report__pb2.DeleteReportRequest.FromString,
                    response_serializer=apps_dot_report_dot_report__pb2.DeleteReportResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=apps_dot_report_dot_report__pb2.ListReportRequest.FromString,
                    response_serializer=apps_dot_report_dot_report__pb2.ListReportResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=apps_dot_report_dot_report__pb2.GetReportRequest.FromString,
                    response_serializer=apps_dot_report_dot_report__pb2.GetReportResponse.SerializeToString,
            ),
            'GenerateReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateReport,
                    request_deserializer=apps_dot_report_dot_report__pb2.GenerateReportRequest.FromString,
                    response_serializer=apps_dot_report_dot_report__pb2.GenerateReportResponse.SerializeToString,
            ),
            'SendByEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.SendByEmail,
                    request_deserializer=apps_dot_report_dot_report__pb2.SendByEmailRequest.FromString,
                    response_serializer=apps_dot_report_dot_report__pb2.SendByEmailResponse.SerializeToString,
            ),
            'SetDefaultReport': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDefaultReport,
                    request_deserializer=apps_dot_report_dot_report__pb2.SetDefaultReportRequest.FromString,
                    response_serializer=apps_dot_report_dot_report__pb2.SetDefaultReportResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'report.ReportService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('report.ReportService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReportService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/report.ReportService/Create',
            apps_dot_report_dot_report__pb2.CreateReportRequest.SerializeToString,
            apps_dot_report_dot_report__pb2.CreateReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/report.ReportService/Update',
            apps_dot_report_dot_report__pb2.UpdateReportRequest.SerializeToString,
            apps_dot_report_dot_report__pb2.UpdateReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/report.ReportService/Delete',
            apps_dot_report_dot_report__pb2.DeleteReportRequest.SerializeToString,
            apps_dot_report_dot_report__pb2.DeleteReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/report.ReportService/List',
            apps_dot_report_dot_report__pb2.ListReportRequest.SerializeToString,
            apps_dot_report_dot_report__pb2.ListReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/report.ReportService/Get',
            apps_dot_report_dot_report__pb2.GetReportRequest.SerializeToString,
            apps_dot_report_dot_report__pb2.GetReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/report.ReportService/GenerateReport',
            apps_dot_report_dot_report__pb2.GenerateReportRequest.SerializeToString,
            apps_dot_report_dot_report__pb2.GenerateReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendByEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/report.ReportService/SendByEmail',
            apps_dot_report_dot_report__pb2.SendByEmailRequest.SerializeToString,
            apps_dot_report_dot_report__pb2.SendByEmailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDefaultReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/report.ReportService/SetDefaultReport',
            apps_dot_report_dot_report__pb2.SetDefaultReportRequest.SerializeToString,
            apps_dot_report_dot_report__pb2.SetDefaultReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
