syntax = "proto3";

package import_mapping;

import "google/api/annotations.proto";

import "plugins/validate/validate.proto";

import "plugins/service/service.proto";

import "filter/filter.proto";

import "common/metadata/metadata.proto";

option go_package = "comps/pb/apps/importacao";

// Serviço Importacao com operações CRUD
service ImportService {
  rpc Create ( CreateImportRequest ) returns ( CreateImportResponse );

  rpc Update ( UpdateImportRequest ) returns ( UpdateImportResponse );

  rpc Delete ( DeleteImportRequest ) returns ( DeleteImportResponse );

  rpc Get ( GetImportRequest ) returns ( GetImportResponse );

  rpc List ( ListImportRequest ) returns ( ListImportResponse );
}

// Dados do Importacao
message Import {
  string id = 1;

  string name = 2;

  string entity_type = 3; // Tipo de entidade sendo mapeada (ex: pedido, cliente, etc)

  string target_structure = 4; // Caminho do proto de destino (ex: apps/vendas/pedido/pedido.proto)

  map<string, string> field_mapping = 5; // Mapeamento entre campos do arquivo externo e campos da estrutura interna

  bool active = 6; // Status do mapeamento

  string description = 7; // Descrição mais detalhada do mapeamento
}

// Request e Response para criação de Importacao
message CreateImportRequest {
  Import import = 1;
}

message CreateImportResponse {
  Import import = 1;
}

// Request e Response para atualização de Importacao
message UpdateImportRequest {
  string id = 1; // ID da NFSe a ser atualizada

  Import import = 2;

  metadata.FieldMask update_mask = 3;
}

// Request e Response para atualização de Importacao
message UpdateImportResponse {
  Import import = 1;
}

// Request e Response para exclusão de Importacao
message DeleteImportRequest {
  string id = 1;

  bool hard = 2;
}

message DeleteImportResponse {
  string id = 1;
}

// Request para obter um Importacao por ID
message GetImportRequest {
  string id = 1;
}

// Request para obter um Importacao por ID
message GetImportResponse {
  Import import = 1;
}

// Request e Response para listagem de Importacaos
message ListImportRequest {
  repeated string ids = 1;

  uint32 page_size = 2;

  string page_token = 3;

  Filter filter = 5;
}

message ListImportResponse {
  repeated Import import_list = 1;

  string next_page_token = 2;
}
