// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: apps/dfe/tributacao/tributacao.proto

package tributacao

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TributacaoService_Create_FullMethodName                      = "/tributacao.TributacaoService/Create"
	TributacaoService_Update_FullMethodName                      = "/tributacao.TributacaoService/Update"
	TributacaoService_Delete_FullMethodName                      = "/tributacao.TributacaoService/Delete"
	TributacaoService_Get_FullMethodName                         = "/tributacao.TributacaoService/Get"
	TributacaoService_List_FullMethodName                        = "/tributacao.TributacaoService/List"
	TributacaoService_Clone_FullMethodName                       = "/tributacao.TributacaoService/Clone"
	TributacaoService_ListClassificacaoTributaria_FullMethodName = "/tributacao.TributacaoService/ListClassificacaoTributaria"
)

// TributacaoServiceClient is the client API for TributacaoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Serviço Tributacao com operações CRUD
type TributacaoServiceClient interface {
	Create(ctx context.Context, in *CreateTributacaoRequest, opts ...grpc.CallOption) (*CreateTributacaoResponse, error)
	Update(ctx context.Context, in *UpdateTributacaoRequest, opts ...grpc.CallOption) (*UpdateTributacaoResponse, error)
	Delete(ctx context.Context, in *DeleteTributacaoRequest, opts ...grpc.CallOption) (*DeleteTributacaoResponse, error)
	Get(ctx context.Context, in *GetTributacaoRequest, opts ...grpc.CallOption) (*GetTributacaoResponse, error)
	List(ctx context.Context, in *ListTributacaoRequest, opts ...grpc.CallOption) (*ListTributacaoResponse, error)
	Clone(ctx context.Context, in *CloneTributacaoRequest, opts ...grpc.CallOption) (*CloneTributacaoResponse, error)
	// Tabela de classificação tributária, restrita aos códigos válidos para NF-e e NFC-e
	ListClassificacaoTributaria(ctx context.Context, in *ListClassificacaoTributariaRequest, opts ...grpc.CallOption) (*ListClassificacaoTributariaResponse, error)
}

type tributacaoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTributacaoServiceClient(cc grpc.ClientConnInterface) TributacaoServiceClient {
	return &tributacaoServiceClient{cc}
}

func (c *tributacaoServiceClient) Create(ctx context.Context, in *CreateTributacaoRequest, opts ...grpc.CallOption) (*CreateTributacaoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTributacaoResponse)
	err := c.cc.Invoke(ctx, TributacaoService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tributacaoServiceClient) Update(ctx context.Context, in *UpdateTributacaoRequest, opts ...grpc.CallOption) (*UpdateTributacaoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTributacaoResponse)
	err := c.cc.Invoke(ctx, TributacaoService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tributacaoServiceClient) Delete(ctx context.Context, in *DeleteTributacaoRequest, opts ...grpc.CallOption) (*DeleteTributacaoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTributacaoResponse)
	err := c.cc.Invoke(ctx, TributacaoService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tributacaoServiceClient) Get(ctx context.Context, in *GetTributacaoRequest, opts ...grpc.CallOption) (*GetTributacaoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTributacaoResponse)
	err := c.cc.Invoke(ctx, TributacaoService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tributacaoServiceClient) List(ctx context.Context, in *ListTributacaoRequest, opts ...grpc.CallOption) (*ListTributacaoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTributacaoResponse)
	err := c.cc.Invoke(ctx, TributacaoService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tributacaoServiceClient) Clone(ctx context.Context, in *CloneTributacaoRequest, opts ...grpc.CallOption) (*CloneTributacaoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloneTributacaoResponse)
	err := c.cc.Invoke(ctx, TributacaoService_Clone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tributacaoServiceClient) ListClassificacaoTributaria(ctx context.Context, in *ListClassificacaoTributariaRequest, opts ...grpc.CallOption) (*ListClassificacaoTributariaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListClassificacaoTributariaResponse)
	err := c.cc.Invoke(ctx, TributacaoService_ListClassificacaoTributaria_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TributacaoServiceServer is the server API for TributacaoService service.
// All implementations must embed UnimplementedTributacaoServiceServer
// for forward compatibility.
//
// Serviço Tributacao com operações CRUD
type TributacaoServiceServer interface {
	Create(context.Context, *CreateTributacaoRequest) (*CreateTributacaoResponse, error)
	Update(context.Context, *UpdateTributacaoRequest) (*UpdateTributacaoResponse, error)
	Delete(context.Context, *DeleteTributacaoRequest) (*DeleteTributacaoResponse, error)
	Get(context.Context, *GetTributacaoRequest) (*GetTributacaoResponse, error)
	List(context.Context, *ListTributacaoRequest) (*ListTributacaoResponse, error)
	Clone(context.Context, *CloneTributacaoRequest) (*CloneTributacaoResponse, error)
	// Tabela de classificação tributária, restrita aos códigos válidos para NF-e e NFC-e
	ListClassificacaoTributaria(context.Context, *ListClassificacaoTributariaRequest) (*ListClassificacaoTributariaResponse, error)
	mustEmbedUnimplementedTributacaoServiceServer()
}

// UnimplementedTributacaoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTributacaoServiceServer struct{}

func (UnimplementedTributacaoServiceServer) Create(context.Context, *CreateTributacaoRequest) (*CreateTributacaoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedTributacaoServiceServer) Update(context.Context, *UpdateTributacaoRequest) (*UpdateTributacaoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedTributacaoServiceServer) Delete(context.Context, *DeleteTributacaoRequest) (*DeleteTributacaoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedTributacaoServiceServer) Get(context.Context, *GetTributacaoRequest) (*GetTributacaoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedTributacaoServiceServer) List(context.Context, *ListTributacaoRequest) (*ListTributacaoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedTributacaoServiceServer) Clone(context.Context, *CloneTributacaoRequest) (*CloneTributacaoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Clone not implemented")
}
func (UnimplementedTributacaoServiceServer) ListClassificacaoTributaria(context.Context, *ListClassificacaoTributariaRequest) (*ListClassificacaoTributariaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListClassificacaoTributaria not implemented")
}
func (UnimplementedTributacaoServiceServer) mustEmbedUnimplementedTributacaoServiceServer() {}
func (UnimplementedTributacaoServiceServer) testEmbeddedByValue()                           {}

// UnsafeTributacaoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TributacaoServiceServer will
// result in compilation errors.
type UnsafeTributacaoServiceServer interface {
	mustEmbedUnimplementedTributacaoServiceServer()
}

func RegisterTributacaoServiceServer(s grpc.ServiceRegistrar, srv TributacaoServiceServer) {
	// If the following call panics, it indicates UnimplementedTributacaoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TributacaoService_ServiceDesc, srv)
}

func _TributacaoService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTributacaoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TributacaoServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TributacaoService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TributacaoServiceServer).Create(ctx, req.(*CreateTributacaoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TributacaoService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTributacaoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TributacaoServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TributacaoService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TributacaoServiceServer).Update(ctx, req.(*UpdateTributacaoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TributacaoService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTributacaoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TributacaoServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TributacaoService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TributacaoServiceServer).Delete(ctx, req.(*DeleteTributacaoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TributacaoService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTributacaoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TributacaoServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TributacaoService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TributacaoServiceServer).Get(ctx, req.(*GetTributacaoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TributacaoService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTributacaoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TributacaoServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TributacaoService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TributacaoServiceServer).List(ctx, req.(*ListTributacaoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TributacaoService_Clone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloneTributacaoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TributacaoServiceServer).Clone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TributacaoService_Clone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TributacaoServiceServer).Clone(ctx, req.(*CloneTributacaoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TributacaoService_ListClassificacaoTributaria_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClassificacaoTributariaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TributacaoServiceServer).ListClassificacaoTributaria(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TributacaoService_ListClassificacaoTributaria_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TributacaoServiceServer).ListClassificacaoTributaria(ctx, req.(*ListClassificacaoTributariaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TributacaoService_ServiceDesc is the grpc.ServiceDesc for TributacaoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TributacaoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tributacao.TributacaoService",
	HandlerType: (*TributacaoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _TributacaoService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _TributacaoService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _TributacaoService_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _TributacaoService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _TributacaoService_List_Handler,
		},
		{
			MethodName: "Clone",
			Handler:    _TributacaoService_Clone_Handler,
		},
		{
			MethodName: "ListClassificacaoTributaria",
			Handler:    _TributacaoService_ListClassificacaoTributaria_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/dfe/tributacao/tributacao.proto",
}
