# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from linksoft_sdk.pb.apps.teamchat import teamchat_pb2 as apps_dot_teamchat_dot_teamchat__pb2


class TeamChatServiceStub:
    """Conversa entre usuários da mesma empresa, com texto e arquivo.

    Cada participante tem o próprio registro da conversa (ConversationMember),
    com o resumo da última mensagem e até onde ele leu. As mensagens ficam em
    Message, uma por registro.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListContacts = channel.unary_unary(
                '/apps.teamchat.TeamChatService/ListContacts',
                request_serializer=apps_dot_teamchat_dot_teamchat__pb2.ListContactsRequest.SerializeToString,
                response_deserializer=apps_dot_teamchat_dot_teamchat__pb2.ListContactsResponse.FromString,
                _registered_method=True)
        self.ListConversations = channel.unary_unary(
                '/apps.teamchat.TeamChatService/ListConversations',
                request_serializer=apps_dot_teamchat_dot_teamchat__pb2.ListConversationsRequest.SerializeToString,
                response_deserializer=apps_dot_teamchat_dot_teamchat__pb2.ListConversationsResponse.FromString,
                _registered_method=True)
        self.StartConversation = channel.unary_unary(
                '/apps.teamchat.TeamChatService/StartConversation',
                request_serializer=apps_dot_teamchat_dot_teamchat__pb2.StartConversationRequest.SerializeToString,
                response_deserializer=apps_dot_teamchat_dot_teamchat__pb2.StartConversationResponse.FromString,
                _registered_method=True)
        self.ListMessages = channel.unary_unary(
                '/apps.teamchat.TeamChatService/ListMessages',
                request_serializer=apps_dot_teamchat_dot_teamchat__pb2.ListMessagesRequest.SerializeToString,
                response_deserializer=apps_dot_teamchat_dot_teamchat__pb2.ListMessagesResponse.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_unary(
                '/apps.teamchat.TeamChatService/SendMessage',
                request_serializer=apps_dot_teamchat_dot_teamchat__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=apps_dot_teamchat_dot_teamchat__pb2.SendMessageResponse.FromString,
                _registered_method=True)
        self.MarkRead = channel.unary_unary(
                '/apps.teamchat.TeamChatService/MarkRead',
                request_serializer=apps_dot_teamchat_dot_teamchat__pb2.MarkReadRequest.SerializeToString,
                response_deserializer=apps_dot_teamchat_dot_teamchat__pb2.MarkReadResponse.FromString,
                _registered_method=True)


class TeamChatServiceServicer:
    """Conversa entre usuários da mesma empresa, com texto e arquivo.

    Cada participante tem o próprio registro da conversa (ConversationMember),
    com o resumo da última mensagem e até onde ele leu. As mensagens ficam em
    Message, uma por registro.
    """

    def ListContacts(self, request, context):
        """Colegas da empresa com quem o usuário pode conversar.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConversations(self, request, context):
        """Conversas do usuário, a mais recente primeiro.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartConversation(self, request, context):
        """Abre a conversa direta com um colega; devolve a existente quando já houver.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMessages(self, request, context):
        """Mensagens da conversa, da mais recente para a mais antiga, em páginas.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkRead(self, request, context):
        """Marca a conversa como lida pelo usuário.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TeamChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListContacts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListContacts,
                    request_deserializer=apps_dot_teamchat_dot_teamchat__pb2.ListContactsRequest.FromString,
                    response_serializer=apps_dot_teamchat_dot_teamchat__pb2.ListContactsResponse.SerializeToString,
            ),
            'ListConversations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConversations,
                    request_deserializer=apps_dot_teamchat_dot_teamchat__pb2.ListConversationsRequest.FromString,
                    response_serializer=apps_dot_teamchat_dot_teamchat__pb2.ListConversationsResponse.SerializeToString,
            ),
            'StartConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.StartConversation,
                    request_deserializer=apps_dot_teamchat_dot_teamchat__pb2.StartConversationRequest.FromString,
                    response_serializer=apps_dot_teamchat_dot_teamchat__pb2.StartConversationResponse.SerializeToString,
            ),
            'ListMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMessages,
                    request_deserializer=apps_dot_teamchat_dot_teamchat__pb2.ListMessagesRequest.FromString,
                    response_serializer=apps_dot_teamchat_dot_teamchat__pb2.ListMessagesResponse.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=apps_dot_teamchat_dot_teamchat__pb2.SendMessageRequest.FromString,
                    response_serializer=apps_dot_teamchat_dot_teamchat__pb2.SendMessageResponse.SerializeToString,
            ),
            'MarkRead': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkRead,
                    request_deserializer=apps_dot_teamchat_dot_teamchat__pb2.MarkReadRequest.FromString,
                    response_serializer=apps_dot_teamchat_dot_teamchat__pb2.MarkReadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'apps.teamchat.TeamChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('apps.teamchat.TeamChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TeamChatService:
    """Conversa entre usuários da mesma empresa, com texto e arquivo.

    Cada participante tem o próprio registro da conversa (ConversationMember),
    com o resumo da última mensagem e até onde ele leu. As mensagens ficam em
    Message, uma por registro.
    """

    @staticmethod
    def ListContacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apps.teamchat.TeamChatService/ListContacts',
            apps_dot_teamchat_dot_teamchat__pb2.ListContactsRequest.SerializeToString,
            apps_dot_teamchat_dot_teamchat__pb2.ListContactsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListConversations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apps.teamchat.TeamChatService/ListConversations',
            apps_dot_teamchat_dot_teamchat__pb2.ListConversationsRequest.SerializeToString,
            apps_dot_teamchat_dot_teamchat__pb2.ListConversationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apps.teamchat.TeamChatService/StartConversation',
            apps_dot_teamchat_dot_teamchat__pb2.StartConversationRequest.SerializeToString,
            apps_dot_teamchat_dot_teamchat__pb2.StartConversationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apps.teamchat.TeamChatService/ListMessages',
            apps_dot_teamchat_dot_teamchat__pb2.ListMessagesRequest.SerializeToString,
            apps_dot_teamchat_dot_teamchat__pb2.ListMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apps.teamchat.TeamChatService/SendMessage',
            apps_dot_teamchat_dot_teamchat__pb2.SendMessageRequest.SerializeToString,
            apps_dot_teamchat_dot_teamchat__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apps.teamchat.TeamChatService/MarkRead',
            apps_dot_teamchat_dot_teamchat__pb2.MarkReadRequest.SerializeToString,
            apps_dot_teamchat_dot_teamchat__pb2.MarkReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
