syntax = "proto3";

package crm_timeline;

import "google/api/annotations.proto";

import "plugins/validate/validate.proto";

import "plugins/service/service.proto";

import "filter/filter.proto";

import "common/metadata/metadata.proto";

import "google/protobuf/timestamp.proto";

option go_package = "comps/pb/apps/crm/timeline";

service TimelineEventService {
  rpc Create ( CreateRequest ) returns ( CreateResponse );

  rpc Update ( UpdateRequest ) returns ( UpdateResponse );

  rpc Delete ( DeleteRequest ) returns ( DeleteResponse );

  rpc Get ( GetRequest ) returns ( GetResponse );

  rpc List ( ListRequest ) returns ( ListResponse );
}

message TimelineEvent {
  string id = 1;

  string reference_id = 2;

  string title = 3;

  string detail = 4;

  google.protobuf.Timestamp occurred_at = 5;

  google.protobuf.Timestamp created_at = 6;

  google.protobuf.Timestamp updated_at = 7;

  string person_id = 8;

  string event_type = 9;

  string origin = 10;

  string user_id = 11;

  string user_name = 12;
}

message CreateRequest {
  TimelineEvent timeline_event = 1;
}

message CreateResponse {
  TimelineEvent timeline_event = 1;
}

message UpdateRequest {
  string id = 1;

  TimelineEvent timeline_event = 2;

  metadata.FieldMask update_mask = 3;
}

message UpdateResponse {
  TimelineEvent timeline_event = 1;
}

message DeleteRequest {
  string id = 1;

  bool hard = 2;
}

message DeleteResponse {
  string id = 1;
}

message GetRequest {
  string id = 1;
}

message GetResponse {
  TimelineEvent timeline_event = 1;
}

message ListRequest {
  repeated string ids = 1;

  string reference_id = 2;

  google.protobuf.Timestamp occurred_at_gte = 3;

  google.protobuf.Timestamp occurred_at_lte = 4;

  Filter filter = 5;

  string person_id = 6;

  string event_type = 7;
}

message ListResponse {
  repeated TimelineEvent timeline_event_list = 1;
}
