// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: apps/dfe/cce/cce.proto

package cce

import (
	report "github.com/linksoft-dev/sdks/go/pb/apps/report"
	metadata "github.com/linksoft-dev/sdks/go/pb/common/metadata"
	filter "github.com/linksoft-dev/sdks/go/pb/filter"
	_ "github.com/linksoft-dev/sdks/go/pb/plugins/service"
	_ "github.com/linksoft-dev/sdks/go/pb/plugins/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Dados do Cce
type Cce struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=createdAt,proto3" json:"createdAt,omitempty"` // Data de criação
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"` // Data de atualização
	UserId              string                 `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`       // ID do usuário que realizou a ação
	UserName            string                 `protobuf:"bytes,4,opt,name=userName,proto3" json:"userName,omitempty"`   // Nome do usuário que realizou a ação
	Id                  string                 `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	Chave               string                 `protobuf:"bytes,6,opt,name=chave,proto3" json:"chave,omitempty"`
	Correcao            string                 `protobuf:"bytes,7,opt,name=correcao,proto3" json:"correcao,omitempty"`
	Ambiente            string                 `protobuf:"bytes,8,opt,name=ambiente,proto3" json:"ambiente,omitempty"`
	Situacao            string                 `protobuf:"bytes,9,opt,name=situacao,proto3" json:"situacao,omitempty"`
	Protocolo           string                 `protobuf:"bytes,10,opt,name=protocolo,proto3" json:"protocolo,omitempty"`
	Sequencia           int32                  `protobuf:"varint,11,opt,name=sequencia,proto3" json:"sequencia,omitempty"`
	XmlAutorizacao      string                 `protobuf:"bytes,12,opt,name=xmlAutorizacao,proto3" json:"xmlAutorizacao,omitempty"`
	DataHoraAutorizacao *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=dataHoraAutorizacao,proto3" json:"dataHoraAutorizacao,omitempty"`
	Rejeicoes           []*Rejeicao            `protobuf:"bytes,14,rep,name=rejeicoes,proto3" json:"rejeicoes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Cce) Reset() {
	*x = Cce{}
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cce) ProtoMessage() {}

func (x *Cce) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cce.ProtoReflect.Descriptor instead.
func (*Cce) Descriptor() ([]byte, []int) {
	return file_apps_dfe_cce_cce_proto_rawDescGZIP(), []int{0}
}

func (x *Cce) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Cce) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Cce) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Cce) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Cce) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cce) GetChave() string {
	if x != nil {
		return x.Chave
	}
	return ""
}

func (x *Cce) GetCorrecao() string {
	if x != nil {
		return x.Correcao
	}
	return ""
}

func (x *Cce) GetAmbiente() string {
	if x != nil {
		return x.Ambiente
	}
	return ""
}

func (x *Cce) GetSituacao() string {
	if x != nil {
		return x.Situacao
	}
	return ""
}

func (x *Cce) GetProtocolo() string {
	if x != nil {
		return x.Protocolo
	}
	return ""
}

func (x *Cce) GetSequencia() int32 {
	if x != nil {
		return x.Sequencia
	}
	return 0
}

func (x *Cce) GetXmlAutorizacao() string {
	if x != nil {
		return x.XmlAutorizacao
	}
	return ""
}

func (x *Cce) GetDataHoraAutorizacao() *timestamppb.Timestamp {
	if x != nil {
		return x.DataHoraAutorizacao
	}
	return nil
}

func (x *Cce) GetRejeicoes() []*Rejeicao {
	if x != nil {
		return x.Rejeicoes
	}
	return nil
}

type Rejeicao struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DataHora            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=dataHora,proto3" json:"dataHora,omitempty"`
	DataHoraSituacaoDoc *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=dataHoraSituacaoDoc,proto3" json:"dataHoraSituacaoDoc,omitempty"`
	Cstat               string                 `protobuf:"bytes,4,opt,name=cstat,proto3" json:"cstat,omitempty"`
	Mensagem            string                 `protobuf:"bytes,5,opt,name=mensagem,proto3" json:"mensagem,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Rejeicao) Reset() {
	*x = Rejeicao{}
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rejeicao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rejeicao) ProtoMessage() {}

func (x *Rejeicao) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rejeicao.ProtoReflect.Descriptor instead.
func (*Rejeicao) Descriptor() ([]byte, []int) {
	return file_apps_dfe_cce_cce_proto_rawDescGZIP(), []int{1}
}

func (x *Rejeicao) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Rejeicao) GetDataHora() *timestamppb.Timestamp {
	if x != nil {
		return x.DataHora
	}
	return nil
}

func (x *Rejeicao) GetDataHoraSituacaoDoc() *timestamppb.Timestamp {
	if x != nil {
		return x.DataHoraSituacaoDoc
	}
	return nil
}

func (x *Rejeicao) GetCstat() string {
	if x != nil {
		return x.Cstat
	}
	return ""
}

func (x *Rejeicao) GetMensagem() string {
	if x != nil {
		return x.Mensagem
	}
	return ""
}

// Request e Response para criação de Cce
type CreateCceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cce           *Cce                   `protobuf:"bytes,1,opt,name=cce,proto3" json:"cce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCceRequest) Reset() {
	*x = CreateCceRequest{}
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCceRequest) ProtoMessage() {}

func (x *CreateCceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCceRequest.ProtoReflect.Descriptor instead.
func (*CreateCceRequest) Descriptor() ([]byte, []int) {
	return file_apps_dfe_cce_cce_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCceRequest) GetCce() *Cce {
	if x != nil {
		return x.Cce
	}
	return nil
}

type CreateCceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cce           *Cce                   `protobuf:"bytes,1,opt,name=cce,proto3" json:"cce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCceResponse) Reset() {
	*x = CreateCceResponse{}
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCceResponse) ProtoMessage() {}

func (x *CreateCceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCceResponse.ProtoReflect.Descriptor instead.
func (*CreateCceResponse) Descriptor() ([]byte, []int) {
	return file_apps_dfe_cce_cce_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCceResponse) GetCce() *Cce {
	if x != nil {
		return x.Cce
	}
	return nil
}

// Request e Response para atualização de Cce
type UpdateCceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ID da NFSe a ser atualizada
	Cce           *Cce                   `protobuf:"bytes,2,opt,name=cce,proto3" json:"cce,omitempty"`
	UpdateMask    *metadata.FieldMask    `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCceRequest) Reset() {
	*x = UpdateCceRequest{}
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCceRequest) ProtoMessage() {}

func (x *UpdateCceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCceRequest.ProtoReflect.Descriptor instead.
func (*UpdateCceRequest) Descriptor() ([]byte, []int) {
	return file_apps_dfe_cce_cce_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCceRequest) GetCce() *Cce {
	if x != nil {
		return x.Cce
	}
	return nil
}

func (x *UpdateCceRequest) GetUpdateMask() *metadata.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// Request e Response para atualização de Cce
type UpdateCceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cce           *Cce                   `protobuf:"bytes,1,opt,name=cce,proto3" json:"cce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCceResponse) Reset() {
	*x = UpdateCceResponse{}
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCceResponse) ProtoMessage() {}

func (x *UpdateCceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCceResponse.ProtoReflect.Descriptor instead.
func (*UpdateCceResponse) Descriptor() ([]byte, []int) {
	return file_apps_dfe_cce_cce_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateCceResponse) GetCce() *Cce {
	if x != nil {
		return x.Cce
	}
	return nil
}

// Request e Response para exclusão de Cce
type DeleteCceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hard          bool                   `protobuf:"varint,2,opt,name=hard,proto3" json:"hard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCceRequest) Reset() {
	*x = DeleteCceRequest{}
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCceRequest) ProtoMessage() {}

func (x *DeleteCceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCceRequest.ProtoReflect.Descriptor instead.
func (*DeleteCceRequest) Descriptor() ([]byte, []int) {
	return file_apps_dfe_cce_cce_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteCceRequest) GetHard() bool {
	if x != nil {
		return x.Hard
	}
	return false
}

type DeleteCceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCceResponse) Reset() {
	*x = DeleteCceResponse{}
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCceResponse) ProtoMessage() {}

func (x *DeleteCceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCceResponse.ProtoReflect.Descriptor instead.
func (*DeleteCceResponse) Descriptor() ([]byte, []int) {
	return file_apps_dfe_cce_cce_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCceResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Request para obter um Cce por ID
type GetCceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCceRequest) Reset() {
	*x = GetCceRequest{}
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCceRequest) ProtoMessage() {}

func (x *GetCceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCceRequest.ProtoReflect.Descriptor instead.
func (*GetCceRequest) Descriptor() ([]byte, []int) {
	return file_apps_dfe_cce_cce_proto_rawDescGZIP(), []int{8}
}

func (x *GetCceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Request para obter um Cce por ID
type GetCceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cce           *Cce                   `protobuf:"bytes,1,opt,name=cce,proto3" json:"cce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCceResponse) Reset() {
	*x = GetCceResponse{}
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCceResponse) ProtoMessage() {}

func (x *GetCceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCceResponse.ProtoReflect.Descriptor instead.
func (*GetCceResponse) Descriptor() ([]byte, []int) {
	return file_apps_dfe_cce_cce_proto_rawDescGZIP(), []int{9}
}

func (x *GetCceResponse) GetCce() *Cce {
	if x != nil {
		return x.Cce
	}
	return nil
}

// Request e Response para listagem de Cces
type ListCceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter        *filter.Filter         `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	CreatedAtGte  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=createdAtGte,proto3" json:"createdAtGte,omitempty"`
	CreatedAtLte  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=createdAtLte,proto3" json:"createdAtLte,omitempty"`
	Situacao      string                 `protobuf:"bytes,8,opt,name=situacao,proto3" json:"situacao,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCceRequest) Reset() {
	*x = ListCceRequest{}
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCceRequest) ProtoMessage() {}

func (x *ListCceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCceRequest.ProtoReflect.Descriptor instead.
func (*ListCceRequest) Descriptor() ([]byte, []int) {
	return file_apps_dfe_cce_cce_proto_rawDescGZIP(), []int{10}
}

func (x *ListCceRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ListCceRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCceRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListCceRequest) GetFilter() *filter.Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListCceRequest) GetCreatedAtGte() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAtGte
	}
	return nil
}

func (x *ListCceRequest) GetCreatedAtLte() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAtLte
	}
	return nil
}

func (x *ListCceRequest) GetSituacao() string {
	if x != nil {
		return x.Situacao
	}
	return ""
}

type ListCceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CceList       []*Cce                 `protobuf:"bytes,1,rep,name=cceList,proto3" json:"cceList,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCceResponse) Reset() {
	*x = ListCceResponse{}
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCceResponse) ProtoMessage() {}

func (x *ListCceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCceResponse.ProtoReflect.Descriptor instead.
func (*ListCceResponse) Descriptor() ([]byte, []int) {
	return file_apps_dfe_cce_cce_proto_rawDescGZIP(), []int{11}
}

func (x *ListCceResponse) GetCceList() []*Cce {
	if x != nil {
		return x.CceList
	}
	return nil
}

func (x *ListCceResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Request para enviar PDF da CC-e por email
type EnviaPdfEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`       // ID da CC-e
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"` // Email para envio
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnviaPdfEmailRequest) Reset() {
	*x = EnviaPdfEmailRequest{}
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnviaPdfEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnviaPdfEmailRequest) ProtoMessage() {}

func (x *EnviaPdfEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnviaPdfEmailRequest.ProtoReflect.Descriptor instead.
func (*EnviaPdfEmailRequest) Descriptor() ([]byte, []int) {
	return file_apps_dfe_cce_cce_proto_rawDescGZIP(), []int{12}
}

func (x *EnviaPdfEmailRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EnviaPdfEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// Resposta ao enviar PDF da CC-e por email
type EnviaPdfEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnviaPdfEmailResponse) Reset() {
	*x = EnviaPdfEmailResponse{}
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnviaPdfEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnviaPdfEmailResponse) ProtoMessage() {}

func (x *EnviaPdfEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnviaPdfEmailResponse.ProtoReflect.Descriptor instead.
func (*EnviaPdfEmailResponse) Descriptor() ([]byte, []int) {
	return file_apps_dfe_cce_cce_proto_rawDescGZIP(), []int{13}
}

func (x *EnviaPdfEmailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Request para imprimir a CC-e
type ImprimirCceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ID da CC-e
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImprimirCceRequest) Reset() {
	*x = ImprimirCceRequest{}
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImprimirCceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImprimirCceRequest) ProtoMessage() {}

func (x *ImprimirCceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImprimirCceRequest.ProtoReflect.Descriptor instead.
func (*ImprimirCceRequest) Descriptor() ([]byte, []int) {
	return file_apps_dfe_cce_cce_proto_rawDescGZIP(), []int{14}
}

func (x *ImprimirCceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Resposta de impressão da CC-e
type ImprimirCceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *report.Response       `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImprimirCceResponse) Reset() {
	*x = ImprimirCceResponse{}
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImprimirCceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImprimirCceResponse) ProtoMessage() {}

func (x *ImprimirCceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dfe_cce_cce_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImprimirCceResponse.ProtoReflect.Descriptor instead.
func (*ImprimirCceResponse) Descriptor() ([]byte, []int) {
	return file_apps_dfe_cce_cce_proto_rawDescGZIP(), []int{15}
}

func (x *ImprimirCceResponse) GetResponse() *report.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_apps_dfe_cce_cce_proto protoreflect.FileDescriptor

const file_apps_dfe_cce_cce_proto_rawDesc = "" +
	"\n" +
	"\x16apps/dfe/cce/cce.proto\x12\x03cce\x1a\x1cgoogle/api/annotations.proto\x1a\x1fplugins/validate/validate.proto\x1a\x1dplugins/service/service.proto\x1a\x13filter/filter.proto\x1a\x1ecommon/metadata/metadata.proto\x1a\x18apps/report/report.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x96\x04\n" +
	"\x03Cce\x128\n" +
	"\tcreatedAt\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\tR\x06userId\x12\x1a\n" +
	"\buserName\x18\x04 \x01(\tR\buserName\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\tR\x02id\x12\x1f\n" +
	"\x05chave\x18\x06 \x01(\tB\t\xfaB\x06r\x04\x10,\x18,R\x05chave\x12\x1a\n" +
	"\bcorrecao\x18\a \x01(\tR\bcorrecao\x12\x1a\n" +
	"\bambiente\x18\b \x01(\tR\bambiente\x12\x1a\n" +
	"\bsituacao\x18\t \x01(\tR\bsituacao\x12\x1c\n" +
	"\tprotocolo\x18\n" +
	" \x01(\tR\tprotocolo\x12\x1c\n" +
	"\tsequencia\x18\v \x01(\x05R\tsequencia\x12&\n" +
	"\x0exmlAutorizacao\x18\f \x01(\tR\x0exmlAutorizacao\x12L\n" +
	"\x13dataHoraAutorizacao\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\x13dataHoraAutorizacao\x12+\n" +
	"\trejeicoes\x18\x0e \x03(\v2\r.cce.RejeicaoR\trejeicoes:\x03\xc0>\x01\"\xd2\x01\n" +
	"\bRejeicao\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\bdataHora\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bdataHora\x12L\n" +
	"\x13dataHoraSituacaoDoc\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x13dataHoraSituacaoDoc\x12\x14\n" +
	"\x05cstat\x18\x04 \x01(\tR\x05cstat\x12\x1a\n" +
	"\bmensagem\x18\x05 \x01(\tR\bmensagem\".\n" +
	"\x10CreateCceRequest\x12\x1a\n" +
	"\x03cce\x18\x01 \x01(\v2\b.cce.CceR\x03cce\"/\n" +
	"\x11CreateCceResponse\x12\x1a\n" +
	"\x03cce\x18\x01 \x01(\v2\b.cce.CceR\x03cce\"t\n" +
	"\x10UpdateCceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\x03cce\x18\x02 \x01(\v2\b.cce.CceR\x03cce\x124\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x13.metadata.FieldMaskR\n" +
	"updateMask\"/\n" +
	"\x11UpdateCceResponse\x12\x1a\n" +
	"\x03cce\x18\x01 \x01(\v2\b.cce.CceR\x03cce\"6\n" +
	"\x10DeleteCceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04hard\x18\x02 \x01(\bR\x04hard\"#\n" +
	"\x11DeleteCceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1f\n" +
	"\rGetCceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\",\n" +
	"\x0eGetCceResponse\x12\x1a\n" +
	"\x03cce\x18\x01 \x01(\v2\b.cce.CceR\x03cce\"\x9b\x02\n" +
	"\x0eListCceRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x1f\n" +
	"\x06filter\x18\x05 \x01(\v2\a.FilterR\x06filter\x12>\n" +
	"\fcreatedAtGte\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\fcreatedAtGte\x12>\n" +
	"\fcreatedAtLte\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\fcreatedAtLte\x12\x1a\n" +
	"\bsituacao\x18\b \x01(\tR\bsituacao\"]\n" +
	"\x0fListCceResponse\x12\"\n" +
	"\acceList\x18\x01 \x03(\v2\b.cce.CceR\acceList\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"<\n" +
	"\x14EnviaPdfEmailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"1\n" +
	"\x15EnviaPdfEmailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"$\n" +
	"\x12ImprimirCceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x13ImprimirCceResponse\x12,\n" +
	"\bresponse\x18\x01 \x01(\v2\x10.report.ResponseR\bresponse2\xb7\x05\n" +
	"\n" +
	"CceService\x12M\n" +
	"\x06Create\x12\x15.cce.CreateCceRequest\x1a\x16.cce.CreateCceResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/api/cces\x12R\n" +
	"\x06Update\x12\x15.cce.UpdateCceRequest\x1a\x16.cce.UpdateCceResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/api/cces/{id}\x12O\n" +
	"\x06Delete\x12\x15.cce.DeleteCceRequest\x1a\x16.cce.DeleteCceResponse\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/api/cces/{id}\x12F\n" +
	"\x03Get\x12\x12.cce.GetCceRequest\x1a\x13.cce.GetCceResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/cces/{id}\x12L\n" +
	"\x04List\x12\x13.cce.ListCceRequest\x1a\x14.cce.ListCceResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/cces/list\x12Q\n" +
	"\x05Envia\x12\x12.cce.GetCceRequest\x1a\x13.cce.GetCceResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/cces/{id}/envia\x12l\n" +
	"\rEnviaPdfEmail\x12\x19.cce.EnviaPdfEmailRequest\x1a\x1a.cce.EnviaPdfEmailResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/cces/{id}/enviaEmail\x12^\n" +
	"\bImprimir\x12\x17.cce.ImprimirCceRequest\x1a\x18.cce.ImprimirCceResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/cces/{id}/imprimirBp\n" +
	"\acom.cceB\bCceProtoP\x01Z/github.com/linksoft-dev/sdks/go/pb/apps/dfe/cce\xa2\x02\x03CXX\xaa\x02\x03Cce\xca\x02\x03Cce\xe2\x02\x0fCce\\GPBMetadata\xea\x02\x03Cceb\x06proto3"

var (
	file_apps_dfe_cce_cce_proto_rawDescOnce sync.Once
	file_apps_dfe_cce_cce_proto_rawDescData []byte
)

func file_apps_dfe_cce_cce_proto_rawDescGZIP() []byte {
	file_apps_dfe_cce_cce_proto_rawDescOnce.Do(func() {
		file_apps_dfe_cce_cce_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_dfe_cce_cce_proto_rawDesc), len(file_apps_dfe_cce_cce_proto_rawDesc)))
	})
	return file_apps_dfe_cce_cce_proto_rawDescData
}

var file_apps_dfe_cce_cce_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_apps_dfe_cce_cce_proto_goTypes = []any{
	(*Cce)(nil),                   // 0: cce.Cce
	(*Rejeicao)(nil),              // 1: cce.Rejeicao
	(*CreateCceRequest)(nil),      // 2: cce.CreateCceRequest
	(*CreateCceResponse)(nil),     // 3: cce.CreateCceResponse
	(*UpdateCceRequest)(nil),      // 4: cce.UpdateCceRequest
	(*UpdateCceResponse)(nil),     // 5: cce.UpdateCceResponse
	(*DeleteCceRequest)(nil),      // 6: cce.DeleteCceRequest
	(*DeleteCceResponse)(nil),     // 7: cce.DeleteCceResponse
	(*GetCceRequest)(nil),         // 8: cce.GetCceRequest
	(*GetCceResponse)(nil),        // 9: cce.GetCceResponse
	(*ListCceRequest)(nil),        // 10: cce.ListCceRequest
	(*ListCceResponse)(nil),       // 11: cce.ListCceResponse
	(*EnviaPdfEmailRequest)(nil),  // 12: cce.EnviaPdfEmailRequest
	(*EnviaPdfEmailResponse)(nil), // 13: cce.EnviaPdfEmailResponse
	(*ImprimirCceRequest)(nil),    // 14: cce.ImprimirCceRequest
	(*ImprimirCceResponse)(nil),   // 15: cce.ImprimirCceResponse
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
	(*metadata.FieldMask)(nil),    // 17: metadata.FieldMask
	(*filter.Filter)(nil),         // 18: Filter
	(*report.Response)(nil),       // 19: report.Response
}
var file_apps_dfe_cce_cce_proto_depIdxs = []int32{
	16, // 0: cce.Cce.createdAt:type_name -> google.protobuf.Timestamp
	16, // 1: cce.Cce.updatedAt:type_name -> google.protobuf.Timestamp
	16, // 2: cce.Cce.dataHoraAutorizacao:type_name -> google.protobuf.Timestamp
	1,  // 3: cce.Cce.rejeicoes:type_name -> cce.Rejeicao
	16, // 4: cce.Rejeicao.dataHora:type_name -> google.protobuf.Timestamp
	16, // 5: cce.Rejeicao.dataHoraSituacaoDoc:type_name -> google.protobuf.Timestamp
	0,  // 6: cce.CreateCceRequest.cce:type_name -> cce.Cce
	0,  // 7: cce.CreateCceResponse.cce:type_name -> cce.Cce
	0,  // 8: cce.UpdateCceRequest.cce:type_name -> cce.Cce
	17, // 9: cce.UpdateCceRequest.update_mask:type_name -> metadata.FieldMask
	0,  // 10: cce.UpdateCceResponse.cce:type_name -> cce.Cce
	0,  // 11: cce.GetCceResponse.cce:type_name -> cce.Cce
	18, // 12: cce.ListCceRequest.filter:type_name -> Filter
	16, // 13: cce.ListCceRequest.createdAtGte:type_name -> google.protobuf.Timestamp
	16, // 14: cce.ListCceRequest.createdAtLte:type_name -> google.protobuf.Timestamp
	0,  // 15: cce.ListCceResponse.cceList:type_name -> cce.Cce
	19, // 16: cce.ImprimirCceResponse.response:type_name -> report.Response
	2,  // 17: cce.CceService.Create:input_type -> cce.CreateCceRequest
	4,  // 18: cce.CceService.Update:input_type -> cce.UpdateCceRequest
	6,  // 19: cce.CceService.Delete:input_type -> cce.DeleteCceRequest
	8,  // 20: cce.CceService.Get:input_type -> cce.GetCceRequest
	10, // 21: cce.CceService.List:input_type -> cce.ListCceRequest
	8,  // 22: cce.CceService.Envia:input_type -> cce.GetCceRequest
	12, // 23: cce.CceService.EnviaPdfEmail:input_type -> cce.EnviaPdfEmailRequest
	14, // 24: cce.CceService.Imprimir:input_type -> cce.ImprimirCceRequest
	3,  // 25: cce.CceService.Create:output_type -> cce.CreateCceResponse
	5,  // 26: cce.CceService.Update:output_type -> cce.UpdateCceResponse
	7,  // 27: cce.CceService.Delete:output_type -> cce.DeleteCceResponse
	9,  // 28: cce.CceService.Get:output_type -> cce.GetCceResponse
	11, // 29: cce.CceService.List:output_type -> cce.ListCceResponse
	9,  // 30: cce.CceService.Envia:output_type -> cce.GetCceResponse
	13, // 31: cce.CceService.EnviaPdfEmail:output_type -> cce.EnviaPdfEmailResponse
	15, // 32: cce.CceService.Imprimir:output_type -> cce.ImprimirCceResponse
	25, // [25:33] is the sub-list for method output_type
	17, // [17:25] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_apps_dfe_cce_cce_proto_init() }
func file_apps_dfe_cce_cce_proto_init() {
	if File_apps_dfe_cce_cce_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_dfe_cce_cce_proto_rawDesc), len(file_apps_dfe_cce_cce_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_dfe_cce_cce_proto_goTypes,
		DependencyIndexes: file_apps_dfe_cce_cce_proto_depIdxs,
		MessageInfos:      file_apps_dfe_cce_cce_proto_msgTypes,
	}.Build()
	File_apps_dfe_cce_cce_proto = out.File
	file_apps_dfe_cce_cce_proto_goTypes = nil
	file_apps_dfe_cce_cce_proto_depIdxs = nil
}
