syntax = "proto3";

package endereco;

import "google/api/annotations.proto";

import "plugins/validate/validate.proto";

import "plugins/service/service.proto";

import "filter/filter.proto";

import "common/metadata/metadata.proto";

import "google/protobuf/timestamp.proto";

option go_package = "comps/pb/apps/endereco";

// Dados do Endereco
message Endereco {
  google.protobuf.Timestamp created_at = 1;

  google.protobuf.Timestamp updated_at = 2;

  string user_id = 3;

  string user_name = 4;

  string id = 5;

  string nome = 6;
}

// Serviço Endereco com operações CRUD
service EnderecoService {
  rpc Create ( CreateRequest ) returns ( CreateResponse );

  rpc Update ( UpdateRequest ) returns ( UpdateResponse );

  rpc Delete ( DeleteRequest ) returns ( DeleteResponse );

  rpc Get ( GetRequest ) returns ( GetResponse );

  rpc List ( ListRequest ) returns ( ListResponse );
}

// Request e Response para criação de Endereco
message CreateRequest {
  Endereco endereco = 1;
}

message CreateResponse {
  Endereco endereco = 1;
}

// Request e Response para atualização de Endereco
message UpdateRequest {
  string id = 1;

  Endereco endereco = 2;

  metadata.FieldMask update_mask = 3;
}

message UpdateResponse {
  Endereco endereco = 1;
}

// Request e Response para exclusão
message DeleteRequest {
  string id = 1;

  bool hard = 2;
}

message DeleteResponse {
  string id = 1;
}

// Request para obter por ID
message GetRequest {
  string id = 1;
}

message GetResponse {
  Endereco endereco = 1;
}

// Request e Response para listagem de Enderecos
message ListRequest {
  repeated string ids = 1;

  uint32 page_size = 2;

  string page_token = 3;

  Filter filter = 5;
}

message ListResponse {
  repeated Endereco endereco_list = 1;

  string next_page_token = 2;
}
