syntax = "proto3";

package nfseservico;

import "google/api/annotations.proto";

import "plugins/service/service.proto";

import "filter/filter.proto";

import "plugins/validate/validate.proto";

import "common/metadata/metadata.proto";

option go_package = "comps/pb/apps/dfe/nfseservico";

message ListaNacional {
  string item = 1;

  string subitem = 2;

  string desdobro_nacional = 3;

  string codigo_tributacao_nacional = 4;
}

message NBS {
  string codigo = 1;

  string descricao = 2;
}

// Serviço de CRUD para os codigos de servicos usado em nota fiscal de serviços
service ServicoService {
  rpc Create ( CreateServicoRequest ) returns ( CreateServicoResponse );

  rpc Update ( UpdateServicoRequest ) returns ( UpdateServicoResponse );

  rpc Delete ( DeleteServicoRequest ) returns ( DeleteServicoResponse );

  rpc List ( ListServicoRequest ) returns ( ListServicoResponse );

  rpc Get ( GetServicoRequest ) returns ( GetServicoResponse );

  rpc Import ( ImportServicoRequest ) returns ( ImportServicoResponse );
}

// Informações do servico usado na NFS-e, lista de servicos vinculados aos CNAES
message Servico {
  string id = 1;

  string nome = 2;

  metadata.BasicFields fields = 3;

  // Codigo do servico no seguinte formato 00.00, esse código do serviço precisa estar vinculado ao CNAE
  string codigo = 4;

  // lista de cnaes que o servivo pode ser usado
  repeated string cnaes = 5;

  ListaNacional lista_nacional = 6;

  NBS nbs = 7;

  // Código de Tributação do Município (ex: 749010400)
  string codigo_tributacao_municipal = 8;
}

// Request e Response para criação de Servicos
message CreateServicoRequest {
  Servico servico = 1; // Dados da Servicos a ser criada
}

message CreateServicoResponse {
  Servico servico = 1;
}

// Request e Response para atualização de Servicos
message UpdateServicoRequest {
  string id = 1; // ID da Servicos a ser atualizada

  Servico servico = 2; // Dados da Servicos a ser atualizada

  metadata.FieldMask update_mask = 3;
}

message UpdateServicoResponse {
  Servico servico = 1;
}

// Request e Response para deleção de Servicos
message DeleteServicoRequest {
  string id = 1; // ID da Servicos a ser deletada

  bool hard = 2;
}

message DeleteServicoResponse {
}

// Request e Response para listagem de Servicos
message ListServicoRequest {
  repeated string ids = 1;

  repeated string cnaes = 2;

  Filter filter = 3;
}

message ListServicoResponse {
  repeated Servico servico_list = 1; // Lista de NFSes
}

// Request para obter uma Servicos
message GetServicoRequest {
  string id = 1; // ID da Servico a ser obtido
}

// Response para obter uma Servicos
message GetServicoResponse {
  Servico servico = 1;
}

message ImportServicoRequest {
  string arquivoBase64 = 1;

  // Se true, sobrescreve campos existentes. Se false, apenas preenche campos vazios.
  bool substituir_existente = 2;
}

message ImportServicoResponse {
  string result = 1;
}
