# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from linksoft_sdk.pb.apps.estoque.estoque import estoque_pb2 as apps_dot_estoque_dot_estoque_dot_estoque__pb2


class EstoqueServiceStub:
    """Serviço de Estoque com operações CRUD
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/estoque.EstoqueService/Create',
                request_serializer=apps_dot_estoque_dot_estoque_dot_estoque__pb2.CreateEstoqueRequest.SerializeToString,
                response_deserializer=apps_dot_estoque_dot_estoque_dot_estoque__pb2.CreateEstoqueResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/estoque.EstoqueService/Update',
                request_serializer=apps_dot_estoque_dot_estoque_dot_estoque__pb2.UpdateEstoqueRequest.SerializeToString,
                response_deserializer=apps_dot_estoque_dot_estoque_dot_estoque__pb2.UpdateEstoqueResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/estoque.EstoqueService/Delete',
                request_serializer=apps_dot_estoque_dot_estoque_dot_estoque__pb2.DeleteEstoqueRequest.SerializeToString,
                response_deserializer=apps_dot_estoque_dot_estoque_dot_estoque__pb2.DeleteEstoqueResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/estoque.EstoqueService/Get',
                request_serializer=apps_dot_estoque_dot_estoque_dot_estoque__pb2.GetEstoqueRequest.SerializeToString,
                response_deserializer=apps_dot_estoque_dot_estoque_dot_estoque__pb2.GetEstoqueResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/estoque.EstoqueService/List',
                request_serializer=apps_dot_estoque_dot_estoque_dot_estoque__pb2.ListEstoqueRequest.SerializeToString,
                response_deserializer=apps_dot_estoque_dot_estoque_dot_estoque__pb2.ListEstoqueResponse.FromString,
                _registered_method=True)


class EstoqueServiceServicer:
    """Serviço de Estoque com operações CRUD
    """

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EstoqueServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=apps_dot_estoque_dot_estoque_dot_estoque__pb2.CreateEstoqueRequest.FromString,
                    response_serializer=apps_dot_estoque_dot_estoque_dot_estoque__pb2.CreateEstoqueResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=apps_dot_estoque_dot_estoque_dot_estoque__pb2.UpdateEstoqueRequest.FromString,
                    response_serializer=apps_dot_estoque_dot_estoque_dot_estoque__pb2.UpdateEstoqueResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=apps_dot_estoque_dot_estoque_dot_estoque__pb2.DeleteEstoqueRequest.FromString,
                    response_serializer=apps_dot_estoque_dot_estoque_dot_estoque__pb2.DeleteEstoqueResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=apps_dot_estoque_dot_estoque_dot_estoque__pb2.GetEstoqueRequest.FromString,
                    response_serializer=apps_dot_estoque_dot_estoque_dot_estoque__pb2.GetEstoqueResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=apps_dot_estoque_dot_estoque_dot_estoque__pb2.ListEstoqueRequest.FromString,
                    response_serializer=apps_dot_estoque_dot_estoque_dot_estoque__pb2.ListEstoqueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'estoque.EstoqueService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('estoque.EstoqueService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EstoqueService:
    """Serviço de Estoque com operações CRUD
    """

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/estoque.EstoqueService/Create',
            apps_dot_estoque_dot_estoque_dot_estoque__pb2.CreateEstoqueRequest.SerializeToString,
            apps_dot_estoque_dot_estoque_dot_estoque__pb2.CreateEstoqueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/estoque.EstoqueService/Update',
            apps_dot_estoque_dot_estoque_dot_estoque__pb2.UpdateEstoqueRequest.SerializeToString,
            apps_dot_estoque_dot_estoque_dot_estoque__pb2.UpdateEstoqueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/estoque.EstoqueService/Delete',
            apps_dot_estoque_dot_estoque_dot_estoque__pb2.DeleteEstoqueRequest.SerializeToString,
            apps_dot_estoque_dot_estoque_dot_estoque__pb2.DeleteEstoqueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/estoque.EstoqueService/Get',
            apps_dot_estoque_dot_estoque_dot_estoque__pb2.GetEstoqueRequest.SerializeToString,
            apps_dot_estoque_dot_estoque_dot_estoque__pb2.GetEstoqueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/estoque.EstoqueService/List',
            apps_dot_estoque_dot_estoque_dot_estoque__pb2.ListEstoqueRequest.SerializeToString,
            apps_dot_estoque_dot_estoque_dot_estoque__pb2.ListEstoqueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
