syntax = "proto3";

package movimentoestoque;

import "plugins/service/service.proto";

import "common/metadata/metadata.proto";

import "google/protobuf/timestamp.proto";

option go_package = "comps/pb/apps/estoque/movimento";

message MovimentoEstoque {
  google.protobuf.Timestamp createdAt = 1; // Data de criação

  string id = 2;

  metadata.BasicFields fields = 3;

  string userId = 4; // ID do usuário que realizou a ação

  string userName = 5;

  string estoqueNome = 6;

  string produtoId = 7;

  string tipo = 8;

  double quantidade = 9;

  double valorUnitario = 10;

  string origem = 11;

  string origemId = 12;

  string origemNumero = 13;

  string obs = 14;

  string pessoaId = 15;

  string pessoaNome = 16;

  string produtoNome = 17;

  double qAnterior = 18;

  double qAtual = 19;

  string variation_id = 20; // ID da variação movimentada

  string variation_sku = 21; // SKU da variação (denormalizado)

  string variation_display_name = 22; // Nome da variação (denormalizado)
}
