// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: apps/posto/convenio/convenio.proto

package convenio

import (
	metadata "github.com/linksoft-dev/sdks/go/pb/common/metadata"
	filter "github.com/linksoft-dev/sdks/go/pb/filter"
	_ "github.com/linksoft-dev/sdks/go/pb/plugins/service"
	_ "github.com/linksoft-dev/sdks/go/pb/plugins/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Fechamento int32

const (
	Fechamento_FECHAMENTO_MENSAL    Fechamento = 0
	Fechamento_FECHAMENTO_QUINZENAL Fechamento = 1
	Fechamento_FECHAMENTO_SEMANAL   Fechamento = 2
)

// Enum value maps for Fechamento.
var (
	Fechamento_name = map[int32]string{
		0: "FECHAMENTO_MENSAL",
		1: "FECHAMENTO_QUINZENAL",
		2: "FECHAMENTO_SEMANAL",
	}
	Fechamento_value = map[string]int32{
		"FECHAMENTO_MENSAL":    0,
		"FECHAMENTO_QUINZENAL": 1,
		"FECHAMENTO_SEMANAL":   2,
	}
)

func (x Fechamento) Enum() *Fechamento {
	p := new(Fechamento)
	*p = x
	return p
}

func (x Fechamento) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Fechamento) Descriptor() protoreflect.EnumDescriptor {
	return file_apps_posto_convenio_convenio_proto_enumTypes[0].Descriptor()
}

func (Fechamento) Type() protoreflect.EnumType {
	return &file_apps_posto_convenio_convenio_proto_enumTypes[0]
}

func (x Fechamento) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Fechamento.Descriptor instead.
func (Fechamento) EnumDescriptor() ([]byte, []int) {
	return file_apps_posto_convenio_convenio_proto_rawDescGZIP(), []int{0}
}

type Convenio struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UserId    string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName  string                 `protobuf:"bytes,4,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Id        string                 `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	Fields    *metadata.BasicFields  `protobuf:"bytes,6,opt,name=fields,proto3" json:"fields,omitempty"`
	// Cliente do convênio. Cada cliente tem um convênio só.
	PessoaId   string `protobuf:"bytes,7,opt,name=pessoa_id,json=pessoaId,proto3" json:"pessoa_id,omitempty"`
	PessoaNome string `protobuf:"bytes,8,opt,name=pessoa_nome,json=pessoaNome,proto3" json:"pessoa_nome,omitempty"`
	Ativo      bool   `protobuf:"varint,9,opt,name=ativo,proto3" json:"ativo,omitempty"`
	// Período da fatura. Mensal fecha no dia_fechamento (no último dia do mês, quando ele é mais
	// curto); quinzenal fecha no dia 15 e no último dia do mês; semanal fecha no dia da semana
	// dia_fechamento (1 segunda-feira ... 7 domingo). A fatura sai no dia seguinte ao fechamento,
	// com as vendas até o fim do dia do fechamento.
	Fechamento    Fechamento `protobuf:"varint,10,opt,name=fechamento,proto3,enum=convenio.Fechamento" json:"fechamento,omitempty"`
	DiaFechamento int32      `protobuf:"varint,11,opt,name=dia_fechamento,json=diaFechamento,proto3" json:"dia_fechamento,omitempty"`
	// Dias entre o fechamento e o vencimento da fatura.
	PrazoVencimentoDias int32 `protobuf:"varint,12,opt,name=prazo_vencimento_dias,json=prazoVencimentoDias,proto3" json:"prazo_vencimento_dias,omitempty"`
	// Forma de pagamento a prazo das vendas do convênio: os títulos dela entram na fatura.
	FormaPagamentoId   string `protobuf:"bytes,13,opt,name=forma_pagamento_id,json=formaPagamentoId,proto3" json:"forma_pagamento_id,omitempty"`
	FormaPagamentoNome string `protobuf:"bytes,14,opt,name=forma_pagamento_nome,json=formaPagamentoNome,proto3" json:"forma_pagamento_nome,omitempty"`
	// A venda do convênio sai com NF-e (modelo 55) em vez de NFC-e.
	EmiteNfe bool `protobuf:"varint,15,opt,name=emite_nfe,json=emiteNfe,proto3" json:"emite_nfe,omitempty"`
	// A venda exige o km do veículo.
	ExigeKm bool `protobuf:"varint,16,opt,name=exige_km,json=exigeKm,proto3" json:"exige_km,omitempty"`
	// A venda exige o nome do motorista.
	ExigeMotorista bool `protobuf:"varint,17,opt,name=exige_motorista,json=exigeMotorista,proto3" json:"exige_motorista,omitempty"`
	// Recusa a venda quando o cliente tem título vencido há mais que estes dias. Zero não bloqueia.
	BloqueiaAtrasoDias int32  `protobuf:"varint,18,opt,name=bloqueia_atraso_dias,json=bloqueiaAtrasoDias,proto3" json:"bloqueia_atraso_dias,omitempty"`
	Obs                string `protobuf:"bytes,19,opt,name=obs,proto3" json:"obs,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Convenio) Reset() {
	*x = Convenio{}
	mi := &file_apps_posto_convenio_convenio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Convenio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Convenio) ProtoMessage() {}

func (x *Convenio) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_convenio_convenio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Convenio.ProtoReflect.Descriptor instead.
func (*Convenio) Descriptor() ([]byte, []int) {
	return file_apps_posto_convenio_convenio_proto_rawDescGZIP(), []int{0}
}

func (x *Convenio) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Convenio) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Convenio) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Convenio) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Convenio) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Convenio) GetFields() *metadata.BasicFields {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Convenio) GetPessoaId() string {
	if x != nil {
		return x.PessoaId
	}
	return ""
}

func (x *Convenio) GetPessoaNome() string {
	if x != nil {
		return x.PessoaNome
	}
	return ""
}

func (x *Convenio) GetAtivo() bool {
	if x != nil {
		return x.Ativo
	}
	return false
}

func (x *Convenio) GetFechamento() Fechamento {
	if x != nil {
		return x.Fechamento
	}
	return Fechamento_FECHAMENTO_MENSAL
}

func (x *Convenio) GetDiaFechamento() int32 {
	if x != nil {
		return x.DiaFechamento
	}
	return 0
}

func (x *Convenio) GetPrazoVencimentoDias() int32 {
	if x != nil {
		return x.PrazoVencimentoDias
	}
	return 0
}

func (x *Convenio) GetFormaPagamentoId() string {
	if x != nil {
		return x.FormaPagamentoId
	}
	return ""
}

func (x *Convenio) GetFormaPagamentoNome() string {
	if x != nil {
		return x.FormaPagamentoNome
	}
	return ""
}

func (x *Convenio) GetEmiteNfe() bool {
	if x != nil {
		return x.EmiteNfe
	}
	return false
}

func (x *Convenio) GetExigeKm() bool {
	if x != nil {
		return x.ExigeKm
	}
	return false
}

func (x *Convenio) GetExigeMotorista() bool {
	if x != nil {
		return x.ExigeMotorista
	}
	return false
}

func (x *Convenio) GetBloqueiaAtrasoDias() int32 {
	if x != nil {
		return x.BloqueiaAtrasoDias
	}
	return 0
}

func (x *Convenio) GetObs() string {
	if x != nil {
		return x.Obs
	}
	return ""
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Convenio      *Convenio              `protobuf:"bytes,1,opt,name=convenio,proto3" json:"convenio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_apps_posto_convenio_convenio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_convenio_convenio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_apps_posto_convenio_convenio_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequest) GetConvenio() *Convenio {
	if x != nil {
		return x.Convenio
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Convenio      *Convenio              `protobuf:"bytes,1,opt,name=convenio,proto3" json:"convenio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_apps_posto_convenio_convenio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_convenio_convenio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_apps_posto_convenio_convenio_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResponse) GetConvenio() *Convenio {
	if x != nil {
		return x.Convenio
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Convenio      *Convenio              `protobuf:"bytes,2,opt,name=convenio,proto3" json:"convenio,omitempty"`
	UpdateMask    *metadata.FieldMask    `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_apps_posto_convenio_convenio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_convenio_convenio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_apps_posto_convenio_convenio_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRequest) GetConvenio() *Convenio {
	if x != nil {
		return x.Convenio
	}
	return nil
}

func (x *UpdateRequest) GetUpdateMask() *metadata.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Convenio      *Convenio              `protobuf:"bytes,1,opt,name=convenio,proto3" json:"convenio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_apps_posto_convenio_convenio_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_convenio_convenio_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_apps_posto_convenio_convenio_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateResponse) GetConvenio() *Convenio {
	if x != nil {
		return x.Convenio
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hard          bool                   `protobuf:"varint,2,opt,name=hard,proto3" json:"hard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_apps_posto_convenio_convenio_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_convenio_convenio_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_apps_posto_convenio_convenio_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteRequest) GetHard() bool {
	if x != nil {
		return x.Hard
	}
	return false
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_apps_posto_convenio_convenio_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_convenio_convenio_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_apps_posto_convenio_convenio_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_apps_posto_convenio_convenio_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_convenio_convenio_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_apps_posto_convenio_convenio_proto_rawDescGZIP(), []int{7}
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Convenio      *Convenio              `protobuf:"bytes,1,opt,name=convenio,proto3" json:"convenio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_apps_posto_convenio_convenio_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_convenio_convenio_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_apps_posto_convenio_convenio_proto_rawDescGZIP(), []int{8}
}

func (x *GetResponse) GetConvenio() *Convenio {
	if x != nil {
		return x.Convenio
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter        *filter.Filter         `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_apps_posto_convenio_convenio_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_convenio_convenio_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_apps_posto_convenio_convenio_proto_rawDescGZIP(), []int{9}
}

func (x *ListRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ListRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListRequest) GetFilter() *filter.Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvenioList  []*Convenio            `protobuf:"bytes,1,rep,name=convenio_list,json=convenioList,proto3" json:"convenio_list,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_apps_posto_convenio_convenio_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_convenio_convenio_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_apps_posto_convenio_convenio_proto_rawDescGZIP(), []int{10}
}

func (x *ListResponse) GetConvenioList() []*Convenio {
	if x != nil {
		return x.ConvenioList
	}
	return nil
}

func (x *ListResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type FaturaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FaturaRequest) Reset() {
	*x = FaturaRequest{}
	mi := &file_apps_posto_convenio_convenio_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaturaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaturaRequest) ProtoMessage() {}

func (x *FaturaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_convenio_convenio_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaturaRequest.ProtoReflect.Descriptor instead.
func (*FaturaRequest) Descriptor() ([]byte, []int) {
	return file_apps_posto_convenio_convenio_proto_rawDescGZIP(), []int{11}
}

func (x *FaturaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FaturaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id da conta a receber da fatura; vazio quando não havia título em aberto.
	ContaId       string  `protobuf:"bytes,1,opt,name=conta_id,json=contaId,proto3" json:"conta_id,omitempty"`
	Titulos       int32   `protobuf:"varint,2,opt,name=titulos,proto3" json:"titulos,omitempty"`
	Valor         float64 `protobuf:"fixed64,3,opt,name=valor,proto3" json:"valor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FaturaResponse) Reset() {
	*x = FaturaResponse{}
	mi := &file_apps_posto_convenio_convenio_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaturaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaturaResponse) ProtoMessage() {}

func (x *FaturaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_convenio_convenio_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaturaResponse.ProtoReflect.Descriptor instead.
func (*FaturaResponse) Descriptor() ([]byte, []int) {
	return file_apps_posto_convenio_convenio_proto_rawDescGZIP(), []int{12}
}

func (x *FaturaResponse) GetContaId() string {
	if x != nil {
		return x.ContaId
	}
	return ""
}

func (x *FaturaResponse) GetTitulos() int32 {
	if x != nil {
		return x.Titulos
	}
	return 0
}

func (x *FaturaResponse) GetValor() float64 {
	if x != nil {
		return x.Valor
	}
	return 0
}

var File_apps_posto_convenio_convenio_proto protoreflect.FileDescriptor

const file_apps_posto_convenio_convenio_proto_rawDesc = "" +
	"\n" +
	"\"apps/posto/convenio/convenio.proto\x12\bconvenio\x1a\x1cgoogle/api/annotations.proto\x1a\x1fplugins/validate/validate.proto\x1a\x1dplugins/service/service.proto\x1a\x13filter/filter.proto\x1a\x1ecommon/metadata/metadata.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x06\n" +
	"\bConvenio\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x04 \x01(\tR\buserName\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\tR\x02id\x12-\n" +
	"\x06fields\x18\x06 \x01(\v2\x15.metadata.BasicFieldsR\x06fields\x12\x1b\n" +
	"\tpessoa_id\x18\a \x01(\tR\bpessoaId\x12\x1f\n" +
	"\vpessoa_nome\x18\b \x01(\tR\n" +
	"pessoaNome\x12\x14\n" +
	"\x05ativo\x18\t \x01(\bR\x05ativo\x124\n" +
	"\n" +
	"fechamento\x18\n" +
	" \x01(\x0e2\x14.convenio.FechamentoR\n" +
	"fechamento\x120\n" +
	"\x0edia_fechamento\x18\v \x01(\x05B\t\xfaB\x06\x1a\x04\x18\x1f(\x00R\rdiaFechamento\x12=\n" +
	"\x15prazo_vencimento_dias\x18\f \x01(\x05B\t\xfaB\x06\x1a\x04\x18x(\x00R\x13prazoVencimentoDias\x12,\n" +
	"\x12forma_pagamento_id\x18\r \x01(\tR\x10formaPagamentoId\x120\n" +
	"\x14forma_pagamento_nome\x18\x0e \x01(\tR\x12formaPagamentoNome\x12\x1b\n" +
	"\temite_nfe\x18\x0f \x01(\bR\bemiteNfe\x12\x19\n" +
	"\bexige_km\x18\x10 \x01(\bR\aexigeKm\x12'\n" +
	"\x0fexige_motorista\x18\x11 \x01(\bR\x0eexigeMotorista\x12<\n" +
	"\x14bloqueia_atraso_dias\x18\x12 \x01(\x05B\n" +
	"\xfaB\a\x1a\x05\x18\xed\x02(\x00R\x12bloqueiaAtrasoDias\x12\x1a\n" +
	"\x03obs\x18\x13 \x01(\tB\b\xfaB\x05r\x03\x18\xf4\x03R\x03obs:\x03\xc0>\x01\"?\n" +
	"\rCreateRequest\x12.\n" +
	"\bconvenio\x18\x01 \x01(\v2\x12.convenio.ConvenioR\bconvenio\"@\n" +
	"\x0eCreateResponse\x12.\n" +
	"\bconvenio\x18\x01 \x01(\v2\x12.convenio.ConvenioR\bconvenio\"\x85\x01\n" +
	"\rUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\bconvenio\x18\x02 \x01(\v2\x12.convenio.ConvenioR\bconvenio\x124\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x13.metadata.FieldMaskR\n" +
	"updateMask\"@\n" +
	"\x0eUpdateResponse\x12.\n" +
	"\bconvenio\x18\x01 \x01(\v2\x12.convenio.ConvenioR\bconvenio\"3\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04hard\x18\x02 \x01(\bR\x04hard\" \n" +
	"\x0eDeleteResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\vGetResponse\x12.\n" +
	"\bconvenio\x18\x01 \x01(\v2\x12.convenio.ConvenioR\bconvenio\"|\n" +
	"\vListRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x1f\n" +
	"\x06filter\x18\x05 \x01(\v2\a.FilterR\x06filter\"o\n" +
	"\fListResponse\x127\n" +
	"\rconvenio_list\x18\x01 \x03(\v2\x12.convenio.ConvenioR\fconvenioList\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x1f\n" +
	"\rFaturaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"[\n" +
	"\x0eFaturaResponse\x12\x19\n" +
	"\bconta_id\x18\x01 \x01(\tR\acontaId\x12\x18\n" +
	"\atitulos\x18\x02 \x01(\x05R\atitulos\x12\x14\n" +
	"\x05valor\x18\x03 \x01(\x01R\x05valor*U\n" +
	"\n" +
	"Fechamento\x12\x15\n" +
	"\x11FECHAMENTO_MENSAL\x10\x00\x12\x18\n" +
	"\x14FECHAMENTO_QUINZENAL\x10\x01\x12\x16\n" +
	"\x12FECHAMENTO_SEMANAL\x10\x022\xd9\x04\n" +
	"\x0fConvenioService\x12c\n" +
	"\x06Create\x12\x17.convenio.CreateRequest\x1a\x18.convenio.CreateResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/posto/convenios/create\x12c\n" +
	"\x06Update\x12\x17.convenio.UpdateRequest\x1a\x18.convenio.UpdateResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\x1a\x1b/api/posto/convenios/update\x12^\n" +
	"\x06Delete\x12\x17.convenio.DeleteRequest\x1a\x18.convenio.DeleteResponse\"!\x82\xd3\xe4\x93\x02\x1b*\x19/api/posto/convenios/{id}\x12U\n" +
	"\x03Get\x12\x14.convenio.GetRequest\x1a\x15.convenio.GetResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/posto/convenios/{id}\x12[\n" +
	"\x04List\x12\x15.convenio.ListRequest\x1a\x16.convenio.ListResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/posto/convenios/list\x12h\n" +
	"\x06Fatura\x12\x17.convenio.FaturaRequest\x1a\x18.convenio.FaturaResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/posto/convenios/{id}/faturaB\x95\x01\n" +
	"\fcom.convenioB\rConvenioProtoP\x01Z6github.com/linksoft-dev/sdks/go/pb/apps/posto/convenio\xa2\x02\x03CXX\xaa\x02\bConvenio\xca\x02\bConvenio\xe2\x02\x14Convenio\\GPBMetadata\xea\x02\bConveniob\x06proto3"

var (
	file_apps_posto_convenio_convenio_proto_rawDescOnce sync.Once
	file_apps_posto_convenio_convenio_proto_rawDescData []byte
)

func file_apps_posto_convenio_convenio_proto_rawDescGZIP() []byte {
	file_apps_posto_convenio_convenio_proto_rawDescOnce.Do(func() {
		file_apps_posto_convenio_convenio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_posto_convenio_convenio_proto_rawDesc), len(file_apps_posto_convenio_convenio_proto_rawDesc)))
	})
	return file_apps_posto_convenio_convenio_proto_rawDescData
}

var file_apps_posto_convenio_convenio_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_apps_posto_convenio_convenio_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_apps_posto_convenio_convenio_proto_goTypes = []any{
	(Fechamento)(0),               // 0: convenio.Fechamento
	(*Convenio)(nil),              // 1: convenio.Convenio
	(*CreateRequest)(nil),         // 2: convenio.CreateRequest
	(*CreateResponse)(nil),        // 3: convenio.CreateResponse
	(*UpdateRequest)(nil),         // 4: convenio.UpdateRequest
	(*UpdateResponse)(nil),        // 5: convenio.UpdateResponse
	(*DeleteRequest)(nil),         // 6: convenio.DeleteRequest
	(*DeleteResponse)(nil),        // 7: convenio.DeleteResponse
	(*GetRequest)(nil),            // 8: convenio.GetRequest
	(*GetResponse)(nil),           // 9: convenio.GetResponse
	(*ListRequest)(nil),           // 10: convenio.ListRequest
	(*ListResponse)(nil),          // 11: convenio.ListResponse
	(*FaturaRequest)(nil),         // 12: convenio.FaturaRequest
	(*FaturaResponse)(nil),        // 13: convenio.FaturaResponse
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
	(*metadata.BasicFields)(nil),  // 15: metadata.BasicFields
	(*metadata.FieldMask)(nil),    // 16: metadata.FieldMask
	(*filter.Filter)(nil),         // 17: Filter
}
var file_apps_posto_convenio_convenio_proto_depIdxs = []int32{
	14, // 0: convenio.Convenio.created_at:type_name -> google.protobuf.Timestamp
	14, // 1: convenio.Convenio.updated_at:type_name -> google.protobuf.Timestamp
	15, // 2: convenio.Convenio.fields:type_name -> metadata.BasicFields
	0,  // 3: convenio.Convenio.fechamento:type_name -> convenio.Fechamento
	1,  // 4: convenio.CreateRequest.convenio:type_name -> convenio.Convenio
	1,  // 5: convenio.CreateResponse.convenio:type_name -> convenio.Convenio
	1,  // 6: convenio.UpdateRequest.convenio:type_name -> convenio.Convenio
	16, // 7: convenio.UpdateRequest.update_mask:type_name -> metadata.FieldMask
	1,  // 8: convenio.UpdateResponse.convenio:type_name -> convenio.Convenio
	1,  // 9: convenio.GetResponse.convenio:type_name -> convenio.Convenio
	17, // 10: convenio.ListRequest.filter:type_name -> Filter
	1,  // 11: convenio.ListResponse.convenio_list:type_name -> convenio.Convenio
	2,  // 12: convenio.ConvenioService.Create:input_type -> convenio.CreateRequest
	4,  // 13: convenio.ConvenioService.Update:input_type -> convenio.UpdateRequest
	6,  // 14: convenio.ConvenioService.Delete:input_type -> convenio.DeleteRequest
	8,  // 15: convenio.ConvenioService.Get:input_type -> convenio.GetRequest
	10, // 16: convenio.ConvenioService.List:input_type -> convenio.ListRequest
	12, // 17: convenio.ConvenioService.Fatura:input_type -> convenio.FaturaRequest
	3,  // 18: convenio.ConvenioService.Create:output_type -> convenio.CreateResponse
	5,  // 19: convenio.ConvenioService.Update:output_type -> convenio.UpdateResponse
	7,  // 20: convenio.ConvenioService.Delete:output_type -> convenio.DeleteResponse
	9,  // 21: convenio.ConvenioService.Get:output_type -> convenio.GetResponse
	11, // 22: convenio.ConvenioService.List:output_type -> convenio.ListResponse
	13, // 23: convenio.ConvenioService.Fatura:output_type -> convenio.FaturaResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_apps_posto_convenio_convenio_proto_init() }
func file_apps_posto_convenio_convenio_proto_init() {
	if File_apps_posto_convenio_convenio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_posto_convenio_convenio_proto_rawDesc), len(file_apps_posto_convenio_convenio_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_posto_convenio_convenio_proto_goTypes,
		DependencyIndexes: file_apps_posto_convenio_convenio_proto_depIdxs,
		EnumInfos:         file_apps_posto_convenio_convenio_proto_enumTypes,
		MessageInfos:      file_apps_posto_convenio_convenio_proto_msgTypes,
	}.Build()
	File_apps_posto_convenio_convenio_proto = out.File
	file_apps_posto_convenio_convenio_proto_goTypes = nil
	file_apps_posto_convenio_convenio_proto_depIdxs = nil
}
