syntax = "proto3";

package centrocusto;

import "google/api/annotations.proto";

import "plugins/validate/validate.proto";

import "plugins/service/service.proto";

import "filter/filter.proto";

import "common/metadata/metadata.proto";

import "google/protobuf/timestamp.proto";

import "apps/report/report.proto";

option go_package = "comps/pb/apps/financeiro/centrocusto";

// Serviço CentroCusto com operações CRUD
service CentroCustoService {
  rpc Create ( CreateCentroCustoRequest ) returns ( CreateCentroCustoResponse );

  rpc Update ( UpdateCentroCustoRequest ) returns ( UpdateCentroCustoResponse );

  rpc Delete ( DeleteCentroCustoRequest ) returns ( DeleteCentroCustoResponse );

  rpc Get ( GetCentroCustoRequest ) returns ( GetCentroCustoResponse );

  rpc List ( ListCentroCustoRequest ) returns ( ListCentroCustoResponse );

  rpc Report ( ReportRequest ) returns ( ReportResponse );

  rpc ReportListaSimples ( ListCentroCustoRequest ) returns ( ReportListaSimplesResponse );
}

// Dados do CentroCusto
message CentroCusto {
  google.protobuf.Timestamp createdAt = 1; // Data de criação

  google.protobuf.Timestamp updatedAt = 2; // Data de atualização

  string userId = 3; // ID do usuário que realizou a ação

  string userName = 4; // Nome do usuário que realizou a ação

  string id = 5;

  string nome = 6;

  metadata.BasicFields fields = 7;
}

// Request e Response para criação de CentroCusto
message CreateCentroCustoRequest {
  CentroCusto centroCusto = 1;
}

message CreateCentroCustoResponse {
  CentroCusto centroCusto = 1;
}

// Request e Response para atualização de CentroCusto
message UpdateCentroCustoRequest {
  string id = 1; // ID da NFSe a ser atualizada

  CentroCusto centroCusto = 2;

  metadata.FieldMask update_mask = 3;
}

// Request e Response para atualização de CentroCusto
message UpdateCentroCustoResponse {
  CentroCusto centroCusto = 1;
}

// Request e Response para exclusão de CentroCusto
message DeleteCentroCustoRequest {
  string id = 1;

  bool hard = 2;
}

message DeleteCentroCustoResponse {
  string id = 1;
}

// Request para obter um CentroCusto por ID
message GetCentroCustoRequest {
  string id = 1;
}

// Request para obter um CentroCusto por ID
message GetCentroCustoResponse {
  CentroCusto centroCusto = 1;
}

// Request e Response para listagem de CentroCustos
message ListCentroCustoRequest {
  repeated string ids = 1;

  uint32 page_size = 2;

  string page_token = 3;

  Filter filter = 5;
}

message ListCentroCustoResponse {
  repeated CentroCusto centroCustoList = 1;

  string next_page_token = 2;
}

// Response para relatório de listagem simples
message ReportListaSimplesResponse {
  report.Response response = 1;
}

// Request e Response para relatório de CentroCusto
message ReportRequest {
  ListCentroCustoRequest request = 1;

  string reportName = 2;

  string sendByEmail = 3;
}

message ReportResponse {
  report.Response response = 1;
}
