// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: imports/imports.proto

package imports

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImportResponse struct {
	state           protoimpl.MessageState       `protogen:"open.v1"`
	ReportTitle     string                       `protobuf:"bytes,1,opt,name=report_title,json=reportTitle,proto3" json:"report_title,omitempty"`
	Result          string                       `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"` // Resultado da importação
	Success         int64                        `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Failed          int64                        `protobuf:"varint,4,opt,name=failed,proto3" json:"failed,omitempty"`
	Total           int64                        `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	ErrosByCategory map[string]*ImportErrorGroup `protobuf:"bytes,6,rep,name=erros_by_category,json=errosByCategory,proto3" json:"erros_by_category,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Erros agrupados por categoria
	HtmlReport      string                       `protobuf:"bytes,7,opt,name=html_report,json=htmlReport,proto3" json:"html_report,omitempty"`                                                                                            // Relatório de importação em HTML
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ImportResponse) Reset() {
	*x = ImportResponse{}
	mi := &file_imports_imports_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportResponse) ProtoMessage() {}

func (x *ImportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_imports_imports_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportResponse.ProtoReflect.Descriptor instead.
func (*ImportResponse) Descriptor() ([]byte, []int) {
	return file_imports_imports_proto_rawDescGZIP(), []int{0}
}

func (x *ImportResponse) GetReportTitle() string {
	if x != nil {
		return x.ReportTitle
	}
	return ""
}

func (x *ImportResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ImportResponse) GetSuccess() int64 {
	if x != nil {
		return x.Success
	}
	return 0
}

func (x *ImportResponse) GetFailed() int64 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *ImportResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ImportResponse) GetErrosByCategory() map[string]*ImportErrorGroup {
	if x != nil {
		return x.ErrosByCategory
	}
	return nil
}

func (x *ImportResponse) GetHtmlReport() string {
	if x != nil {
		return x.HtmlReport
	}
	return ""
}

type ImportErrorGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errors        []*ImportError         `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportErrorGroup) Reset() {
	*x = ImportErrorGroup{}
	mi := &file_imports_imports_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportErrorGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportErrorGroup) ProtoMessage() {}

func (x *ImportErrorGroup) ProtoReflect() protoreflect.Message {
	mi := &file_imports_imports_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportErrorGroup.ProtoReflect.Descriptor instead.
func (*ImportErrorGroup) Descriptor() ([]byte, []int) {
	return file_imports_imports_proto_rawDescGZIP(), []int{1}
}

func (x *ImportErrorGroup) GetErrors() []*ImportError {
	if x != nil {
		return x.Errors
	}
	return nil
}

// Estrutura de erro de importação
type ImportError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"` // Identificação da conta com erro
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`   // Motivo do erro
	Details       []string               `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"` // Detalhes do erro
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportError) Reset() {
	*x = ImportError{}
	mi := &file_imports_imports_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportError) ProtoMessage() {}

func (x *ImportError) ProtoReflect() protoreflect.Message {
	mi := &file_imports_imports_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportError.ProtoReflect.Descriptor instead.
func (*ImportError) Descriptor() ([]byte, []int) {
	return file_imports_imports_proto_rawDescGZIP(), []int{2}
}

func (x *ImportError) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *ImportError) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ImportError) GetDetails() []string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_imports_imports_proto protoreflect.FileDescriptor

const file_imports_imports_proto_rawDesc = "" +
	"\n" +
	"\x15imports/imports.proto\x12\aimports\"\xed\x02\n" +
	"\x0eImportResponse\x12!\n" +
	"\freport_title\x18\x01 \x01(\tR\vreportTitle\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\x03R\asuccess\x12\x16\n" +
	"\x06failed\x18\x04 \x01(\x03R\x06failed\x12\x14\n" +
	"\x05total\x18\x05 \x01(\x03R\x05total\x12X\n" +
	"\x11erros_by_category\x18\x06 \x03(\v2,.imports.ImportResponse.ErrosByCategoryEntryR\x0ferrosByCategory\x12\x1f\n" +
	"\vhtml_report\x18\a \x01(\tR\n" +
	"htmlReport\x1a]\n" +
	"\x14ErrosByCategoryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.imports.ImportErrorGroupR\x05value:\x028\x01\"@\n" +
	"\x10ImportErrorGroup\x12,\n" +
	"\x06errors\x18\x01 \x03(\v2\x14.imports.ImportErrorR\x06errors\"Y\n" +
	"\vImportError\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x18\n" +
	"\adetails\x18\x03 \x03(\tR\adetailsB\x83\x01\n" +
	"\vcom.importsB\fImportsProtoP\x01Z*github.com/linksoft-dev/sdks/go/pb/imports\xa2\x02\x03IXX\xaa\x02\aImports\xca\x02\aImports\xe2\x02\x13Imports\\GPBMetadata\xea\x02\aImportsb\x06proto3"

var (
	file_imports_imports_proto_rawDescOnce sync.Once
	file_imports_imports_proto_rawDescData []byte
)

func file_imports_imports_proto_rawDescGZIP() []byte {
	file_imports_imports_proto_rawDescOnce.Do(func() {
		file_imports_imports_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_imports_imports_proto_rawDesc), len(file_imports_imports_proto_rawDesc)))
	})
	return file_imports_imports_proto_rawDescData
}

var file_imports_imports_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_imports_imports_proto_goTypes = []any{
	(*ImportResponse)(nil),   // 0: imports.ImportResponse
	(*ImportErrorGroup)(nil), // 1: imports.ImportErrorGroup
	(*ImportError)(nil),      // 2: imports.ImportError
	nil,                      // 3: imports.ImportResponse.ErrosByCategoryEntry
}
var file_imports_imports_proto_depIdxs = []int32{
	3, // 0: imports.ImportResponse.erros_by_category:type_name -> imports.ImportResponse.ErrosByCategoryEntry
	2, // 1: imports.ImportErrorGroup.errors:type_name -> imports.ImportError
	1, // 2: imports.ImportResponse.ErrosByCategoryEntry.value:type_name -> imports.ImportErrorGroup
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_imports_imports_proto_init() }
func file_imports_imports_proto_init() {
	if File_imports_imports_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_imports_imports_proto_rawDesc), len(file_imports_imports_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_imports_imports_proto_goTypes,
		DependencyIndexes: file_imports_imports_proto_depIdxs,
		MessageInfos:      file_imports_imports_proto_msgTypes,
	}.Build()
	File_imports_imports_proto = out.File
	file_imports_imports_proto_goTypes = nil
	file_imports_imports_proto_depIdxs = nil
}
