# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from linksoft_sdk.pb.apps.servico import servico_pb2 as apps_dot_servico_dot_servico__pb2


class ServicoServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/servico.ServicoService/Create',
                request_serializer=apps_dot_servico_dot_servico__pb2.CreateServicoRequest.SerializeToString,
                response_deserializer=apps_dot_servico_dot_servico__pb2.CreateServicoResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/servico.ServicoService/Update',
                request_serializer=apps_dot_servico_dot_servico__pb2.UpdateServicoRequest.SerializeToString,
                response_deserializer=apps_dot_servico_dot_servico__pb2.UpdateServicoResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/servico.ServicoService/Delete',
                request_serializer=apps_dot_servico_dot_servico__pb2.DeleteServicoRequest.SerializeToString,
                response_deserializer=apps_dot_servico_dot_servico__pb2.DeleteServicoResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/servico.ServicoService/Get',
                request_serializer=apps_dot_servico_dot_servico__pb2.GetServicoRequest.SerializeToString,
                response_deserializer=apps_dot_servico_dot_servico__pb2.GetServicoResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/servico.ServicoService/List',
                request_serializer=apps_dot_servico_dot_servico__pb2.ListServicoRequest.SerializeToString,
                response_deserializer=apps_dot_servico_dot_servico__pb2.ListServicoResponse.FromString,
                _registered_method=True)
        self.Import = channel.unary_unary(
                '/servico.ServicoService/Import',
                request_serializer=apps_dot_servico_dot_servico__pb2.ImportServicoRequest.SerializeToString,
                response_deserializer=apps_dot_servico_dot_servico__pb2.ImportServicoResponse.FromString,
                _registered_method=True)
        self.SincronizarModulos = channel.unary_unary(
                '/servico.ServicoService/SincronizarModulos',
                request_serializer=apps_dot_servico_dot_servico__pb2.SincronizarModulosRequest.SerializeToString,
                response_deserializer=apps_dot_servico_dot_servico__pb2.SincronizarModulosResponse.FromString,
                _registered_method=True)
        self.ExecutarAlteracoesConjuntas = channel.unary_unary(
                '/servico.ServicoService/ExecutarAlteracoesConjuntas',
                request_serializer=apps_dot_servico_dot_servico__pb2.AlteracoesConjuntasServicoRequest.SerializeToString,
                response_deserializer=apps_dot_servico_dot_servico__pb2.AlteracoesConjuntasServicoResponse.FromString,
                _registered_method=True)
        self.Report = channel.unary_unary(
                '/servico.ServicoService/Report',
                request_serializer=apps_dot_servico_dot_servico__pb2.ReportRequest.SerializeToString,
                response_deserializer=apps_dot_servico_dot_servico__pb2.ReportResponse.FromString,
                _registered_method=True)
        self.Clone = channel.unary_unary(
                '/servico.ServicoService/Clone',
                request_serializer=apps_dot_servico_dot_servico__pb2.CloneServicoRequest.SerializeToString,
                response_deserializer=apps_dot_servico_dot_servico__pb2.CloneServicoResponse.FromString,
                _registered_method=True)


class ServicoServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Import(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SincronizarModulos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecutarAlteracoesConjuntas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Report(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Clone(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServicoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=apps_dot_servico_dot_servico__pb2.CreateServicoRequest.FromString,
                    response_serializer=apps_dot_servico_dot_servico__pb2.CreateServicoResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=apps_dot_servico_dot_servico__pb2.UpdateServicoRequest.FromString,
                    response_serializer=apps_dot_servico_dot_servico__pb2.UpdateServicoResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=apps_dot_servico_dot_servico__pb2.DeleteServicoRequest.FromString,
                    response_serializer=apps_dot_servico_dot_servico__pb2.DeleteServicoResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=apps_dot_servico_dot_servico__pb2.GetServicoRequest.FromString,
                    response_serializer=apps_dot_servico_dot_servico__pb2.GetServicoResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=apps_dot_servico_dot_servico__pb2.ListServicoRequest.FromString,
                    response_serializer=apps_dot_servico_dot_servico__pb2.ListServicoResponse.SerializeToString,
            ),
            'Import': grpc.unary_unary_rpc_method_handler(
                    servicer.Import,
                    request_deserializer=apps_dot_servico_dot_servico__pb2.ImportServicoRequest.FromString,
                    response_serializer=apps_dot_servico_dot_servico__pb2.ImportServicoResponse.SerializeToString,
            ),
            'SincronizarModulos': grpc.unary_unary_rpc_method_handler(
                    servicer.SincronizarModulos,
                    request_deserializer=apps_dot_servico_dot_servico__pb2.SincronizarModulosRequest.FromString,
                    response_serializer=apps_dot_servico_dot_servico__pb2.SincronizarModulosResponse.SerializeToString,
            ),
            'ExecutarAlteracoesConjuntas': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecutarAlteracoesConjuntas,
                    request_deserializer=apps_dot_servico_dot_servico__pb2.AlteracoesConjuntasServicoRequest.FromString,
                    response_serializer=apps_dot_servico_dot_servico__pb2.AlteracoesConjuntasServicoResponse.SerializeToString,
            ),
            'Report': grpc.unary_unary_rpc_method_handler(
                    servicer.Report,
                    request_deserializer=apps_dot_servico_dot_servico__pb2.ReportRequest.FromString,
                    response_serializer=apps_dot_servico_dot_servico__pb2.ReportResponse.SerializeToString,
            ),
            'Clone': grpc.unary_unary_rpc_method_handler(
                    servicer.Clone,
                    request_deserializer=apps_dot_servico_dot_servico__pb2.CloneServicoRequest.FromString,
                    response_serializer=apps_dot_servico_dot_servico__pb2.CloneServicoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'servico.ServicoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('servico.ServicoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServicoService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/servico.ServicoService/Create',
            apps_dot_servico_dot_servico__pb2.CreateServicoRequest.SerializeToString,
            apps_dot_servico_dot_servico__pb2.CreateServicoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/servico.ServicoService/Update',
            apps_dot_servico_dot_servico__pb2.UpdateServicoRequest.SerializeToString,
            apps_dot_servico_dot_servico__pb2.UpdateServicoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/servico.ServicoService/Delete',
            apps_dot_servico_dot_servico__pb2.DeleteServicoRequest.SerializeToString,
            apps_dot_servico_dot_servico__pb2.DeleteServicoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/servico.ServicoService/Get',
            apps_dot_servico_dot_servico__pb2.GetServicoRequest.SerializeToString,
            apps_dot_servico_dot_servico__pb2.GetServicoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/servico.ServicoService/List',
            apps_dot_servico_dot_servico__pb2.ListServicoRequest.SerializeToString,
            apps_dot_servico_dot_servico__pb2.ListServicoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Import(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/servico.ServicoService/Import',
            apps_dot_servico_dot_servico__pb2.ImportServicoRequest.SerializeToString,
            apps_dot_servico_dot_servico__pb2.ImportServicoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SincronizarModulos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/servico.ServicoService/SincronizarModulos',
            apps_dot_servico_dot_servico__pb2.SincronizarModulosRequest.SerializeToString,
            apps_dot_servico_dot_servico__pb2.SincronizarModulosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecutarAlteracoesConjuntas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/servico.ServicoService/ExecutarAlteracoesConjuntas',
            apps_dot_servico_dot_servico__pb2.AlteracoesConjuntasServicoRequest.SerializeToString,
            apps_dot_servico_dot_servico__pb2.AlteracoesConjuntasServicoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Report(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/servico.ServicoService/Report',
            apps_dot_servico_dot_servico__pb2.ReportRequest.SerializeToString,
            apps_dot_servico_dot_servico__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Clone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/servico.ServicoService/Clone',
            apps_dot_servico_dot_servico__pb2.CloneServicoRequest.SerializeToString,
            apps_dot_servico_dot_servico__pb2.CloneServicoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
