// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: apps/posto/abastecimento/abastecimento.proto

package abastecimento

import (
	metadata "github.com/linksoft-dev/sdks/go/pb/common/metadata"
	filter "github.com/linksoft-dev/sdks/go/pb/filter"
	_ "github.com/linksoft-dev/sdks/go/pb/plugins/service"
	_ "github.com/linksoft-dev/sdks/go/pb/plugins/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Situacao int32

const (
	Situacao_SITUACAO_UNSPECIFIED Situacao = 0
	// Concluído na bomba e ainda sem venda.
	Situacao_SITUACAO_PENDENTE Situacao = 1
	// Reservado por um caixa e incluído numa venda aberta.
	Situacao_SITUACAO_EM_VENDA Situacao = 2
	// A venda foi fechada.
	Situacao_SITUACAO_VENDIDO Situacao = 3
	// Aferição de bico: volume devolvido ao tanque, sem venda.
	Situacao_SITUACAO_AFERICAO Situacao = 4
)

// Enum value maps for Situacao.
var (
	Situacao_name = map[int32]string{
		0: "SITUACAO_UNSPECIFIED",
		1: "SITUACAO_PENDENTE",
		2: "SITUACAO_EM_VENDA",
		3: "SITUACAO_VENDIDO",
		4: "SITUACAO_AFERICAO",
	}
	Situacao_value = map[string]int32{
		"SITUACAO_UNSPECIFIED": 0,
		"SITUACAO_PENDENTE":    1,
		"SITUACAO_EM_VENDA":    2,
		"SITUACAO_VENDIDO":     3,
		"SITUACAO_AFERICAO":    4,
	}
)

func (x Situacao) Enum() *Situacao {
	p := new(Situacao)
	*p = x
	return p
}

func (x Situacao) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Situacao) Descriptor() protoreflect.EnumDescriptor {
	return file_apps_posto_abastecimento_abastecimento_proto_enumTypes[0].Descriptor()
}

func (Situacao) Type() protoreflect.EnumType {
	return &file_apps_posto_abastecimento_abastecimento_proto_enumTypes[0]
}

func (x Situacao) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Situacao.Descriptor instead.
func (Situacao) EnumDescriptor() ([]byte, []int) {
	return file_apps_posto_abastecimento_abastecimento_proto_rawDescGZIP(), []int{0}
}

type Tipo int32

const (
	Tipo_TIPO_UNSPECIFIED Tipo = 0
	Tipo_TIPO_NORMAL      Tipo = 1
	// A própria automação classificou como teste/aferição.
	Tipo_TIPO_AFERICAO Tipo = 2
	// Gerado pela automação a partir da diferença de encerrante (bomba operou sem comunicação).
	Tipo_TIPO_OFFLINE Tipo = 3
)

// Enum value maps for Tipo.
var (
	Tipo_name = map[int32]string{
		0: "TIPO_UNSPECIFIED",
		1: "TIPO_NORMAL",
		2: "TIPO_AFERICAO",
		3: "TIPO_OFFLINE",
	}
	Tipo_value = map[string]int32{
		"TIPO_UNSPECIFIED": 0,
		"TIPO_NORMAL":      1,
		"TIPO_AFERICAO":    2,
		"TIPO_OFFLINE":     3,
	}
)

func (x Tipo) Enum() *Tipo {
	p := new(Tipo)
	*p = x
	return p
}

func (x Tipo) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Tipo) Descriptor() protoreflect.EnumDescriptor {
	return file_apps_posto_abastecimento_abastecimento_proto_enumTypes[1].Descriptor()
}

func (Tipo) Type() protoreflect.EnumType {
	return &file_apps_posto_abastecimento_abastecimento_proto_enumTypes[1]
}

func (x Tipo) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Tipo.Descriptor instead.
func (Tipo) EnumDescriptor() ([]byte, []int) {
	return file_apps_posto_abastecimento_abastecimento_proto_rawDescGZIP(), []int{1}
}

type Abastecimento struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UserId    string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName  string                 `protobuf:"bytes,4,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Id        string                 `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	Fields    *metadata.BasicFields  `protobuf:"bytes,6,opt,name=fields,proto3" json:"fields,omitempty"`
	// Identificação única do abastecimento na automação (marca + id na automação).
	OrigemId          string  `protobuf:"bytes,7,opt,name=origem_id,json=origemId,proto3" json:"origem_id,omitempty"`
	Marca             string  `protobuf:"bytes,8,opt,name=marca,proto3" json:"marca,omitempty"`
	NumBico           int32   `protobuf:"varint,9,opt,name=num_bico,json=numBico,proto3" json:"num_bico,omitempty"`
	NumBomba          string  `protobuf:"bytes,10,opt,name=num_bomba,json=numBomba,proto3" json:"num_bomba,omitempty"`
	NumTanque         string  `protobuf:"bytes,11,opt,name=num_tanque,json=numTanque,proto3" json:"num_tanque,omitempty"`
	ProdutoId         string  `protobuf:"bytes,12,opt,name=produto_id,json=produtoId,proto3" json:"produto_id,omitempty"`
	ProdutoNome       string  `protobuf:"bytes,13,opt,name=produto_nome,json=produtoNome,proto3" json:"produto_nome,omitempty"`
	CodigoAnp         string  `protobuf:"bytes,14,opt,name=codigo_anp,json=codigoAnp,proto3" json:"codigo_anp,omitempty"`
	Volume            float64 `protobuf:"fixed64,15,opt,name=volume,proto3" json:"volume,omitempty"`
	PrecoUnitario     float64 `protobuf:"fixed64,16,opt,name=preco_unitario,json=precoUnitario,proto3" json:"preco_unitario,omitempty"`
	ValorTotal        float64 `protobuf:"fixed64,17,opt,name=valor_total,json=valorTotal,proto3" json:"valor_total,omitempty"`
	EncerranteInicial float64 `protobuf:"fixed64,18,opt,name=encerrante_inicial,json=encerranteInicial,proto3" json:"encerrante_inicial,omitempty"`
	EncerranteFinal   float64 `protobuf:"fixed64,19,opt,name=encerrante_final,json=encerranteFinal,proto3" json:"encerrante_final,omitempty"`
	// Momento em que a bomba concluiu o abastecimento.
	DataHora        *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=data_hora,json=dataHora,proto3" json:"data_hora,omitempty"`
	Situacao        Situacao               `protobuf:"varint,21,opt,name=situacao,proto3,enum=abastecimento.Situacao" json:"situacao,omitempty"`
	Tipo            Tipo                   `protobuf:"varint,22,opt,name=tipo,proto3,enum=abastecimento.Tipo" json:"tipo,omitempty"`
	PedidoId        string                 `protobuf:"bytes,23,opt,name=pedido_id,json=pedidoId,proto3" json:"pedido_id,omitempty"`
	PedidoNumero    int32                  `protobuf:"varint,24,opt,name=pedido_numero,json=pedidoNumero,proto3" json:"pedido_numero,omitempty"`
	ReservaUserId   string                 `protobuf:"bytes,25,opt,name=reserva_user_id,json=reservaUserId,proto3" json:"reserva_user_id,omitempty"`
	ReservaUserName string                 `protobuf:"bytes,26,opt,name=reserva_user_name,json=reservaUserName,proto3" json:"reserva_user_name,omitempty"`
	ReservaEm       *timestamppb.Timestamp `protobuf:"bytes,27,opt,name=reserva_em,json=reservaEm,proto3" json:"reserva_em,omitempty"`
	// Motivo pelo qual o abastecimento não pode ir para a venda (ex.: bico sem cadastro).
	Bloqueio string `protobuf:"bytes,28,opt,name=bloqueio,proto3" json:"bloqueio,omitempty"`
	// Identificação do frentista informada pela automação quando ele se identifica na bomba.
	FrentistaCodigo string `protobuf:"bytes,29,opt,name=frentista_codigo,json=frentistaCodigo,proto3" json:"frentista_codigo,omitempty"`
	// Pessoa do frentista que recebeu o abastecimento.
	FrentistaId   string `protobuf:"bytes,30,opt,name=frentista_id,json=frentistaId,proto3" json:"frentista_id,omitempty"`
	FrentistaNome string `protobuf:"bytes,31,opt,name=frentista_nome,json=frentistaNome,proto3" json:"frentista_nome,omitempty"`
	// Nível de preço em que a bomba cobrou: 1 à vista, 2 a prazo.
	NivelPreco int32 `protobuf:"varint,32,opt,name=nivel_preco,json=nivelPreco,proto3" json:"nivel_preco,omitempty"`
	// Tag do veículo lida na bomba.
	VeiculoTag string `protobuf:"bytes,33,opt,name=veiculo_tag,json=veiculoTag,proto3" json:"veiculo_tag,omitempty"`
	// Veículo de frota identificado pela tag; somente leitura.
	PostoVeiculoId string `protobuf:"bytes,34,opt,name=posto_veiculo_id,json=postoVeiculoId,proto3" json:"posto_veiculo_id,omitempty"`
	PostoPlaca     string `protobuf:"bytes,35,opt,name=posto_placa,json=postoPlaca,proto3" json:"posto_placa,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Abastecimento) Reset() {
	*x = Abastecimento{}
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Abastecimento) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Abastecimento) ProtoMessage() {}

func (x *Abastecimento) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Abastecimento.ProtoReflect.Descriptor instead.
func (*Abastecimento) Descriptor() ([]byte, []int) {
	return file_apps_posto_abastecimento_abastecimento_proto_rawDescGZIP(), []int{0}
}

func (x *Abastecimento) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Abastecimento) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Abastecimento) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Abastecimento) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Abastecimento) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Abastecimento) GetFields() *metadata.BasicFields {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Abastecimento) GetOrigemId() string {
	if x != nil {
		return x.OrigemId
	}
	return ""
}

func (x *Abastecimento) GetMarca() string {
	if x != nil {
		return x.Marca
	}
	return ""
}

func (x *Abastecimento) GetNumBico() int32 {
	if x != nil {
		return x.NumBico
	}
	return 0
}

func (x *Abastecimento) GetNumBomba() string {
	if x != nil {
		return x.NumBomba
	}
	return ""
}

func (x *Abastecimento) GetNumTanque() string {
	if x != nil {
		return x.NumTanque
	}
	return ""
}

func (x *Abastecimento) GetProdutoId() string {
	if x != nil {
		return x.ProdutoId
	}
	return ""
}

func (x *Abastecimento) GetProdutoNome() string {
	if x != nil {
		return x.ProdutoNome
	}
	return ""
}

func (x *Abastecimento) GetCodigoAnp() string {
	if x != nil {
		return x.CodigoAnp
	}
	return ""
}

func (x *Abastecimento) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Abastecimento) GetPrecoUnitario() float64 {
	if x != nil {
		return x.PrecoUnitario
	}
	return 0
}

func (x *Abastecimento) GetValorTotal() float64 {
	if x != nil {
		return x.ValorTotal
	}
	return 0
}

func (x *Abastecimento) GetEncerranteInicial() float64 {
	if x != nil {
		return x.EncerranteInicial
	}
	return 0
}

func (x *Abastecimento) GetEncerranteFinal() float64 {
	if x != nil {
		return x.EncerranteFinal
	}
	return 0
}

func (x *Abastecimento) GetDataHora() *timestamppb.Timestamp {
	if x != nil {
		return x.DataHora
	}
	return nil
}

func (x *Abastecimento) GetSituacao() Situacao {
	if x != nil {
		return x.Situacao
	}
	return Situacao_SITUACAO_UNSPECIFIED
}

func (x *Abastecimento) GetTipo() Tipo {
	if x != nil {
		return x.Tipo
	}
	return Tipo_TIPO_UNSPECIFIED
}

func (x *Abastecimento) GetPedidoId() string {
	if x != nil {
		return x.PedidoId
	}
	return ""
}

func (x *Abastecimento) GetPedidoNumero() int32 {
	if x != nil {
		return x.PedidoNumero
	}
	return 0
}

func (x *Abastecimento) GetReservaUserId() string {
	if x != nil {
		return x.ReservaUserId
	}
	return ""
}

func (x *Abastecimento) GetReservaUserName() string {
	if x != nil {
		return x.ReservaUserName
	}
	return ""
}

func (x *Abastecimento) GetReservaEm() *timestamppb.Timestamp {
	if x != nil {
		return x.ReservaEm
	}
	return nil
}

func (x *Abastecimento) GetBloqueio() string {
	if x != nil {
		return x.Bloqueio
	}
	return ""
}

func (x *Abastecimento) GetFrentistaCodigo() string {
	if x != nil {
		return x.FrentistaCodigo
	}
	return ""
}

func (x *Abastecimento) GetFrentistaId() string {
	if x != nil {
		return x.FrentistaId
	}
	return ""
}

func (x *Abastecimento) GetFrentistaNome() string {
	if x != nil {
		return x.FrentistaNome
	}
	return ""
}

func (x *Abastecimento) GetNivelPreco() int32 {
	if x != nil {
		return x.NivelPreco
	}
	return 0
}

func (x *Abastecimento) GetVeiculoTag() string {
	if x != nil {
		return x.VeiculoTag
	}
	return ""
}

func (x *Abastecimento) GetPostoVeiculoId() string {
	if x != nil {
		return x.PostoVeiculoId
	}
	return ""
}

func (x *Abastecimento) GetPostoPlaca() string {
	if x != nil {
		return x.PostoPlaca
	}
	return ""
}

type GetAbastecimentoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAbastecimentoRequest) Reset() {
	*x = GetAbastecimentoRequest{}
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAbastecimentoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAbastecimentoRequest) ProtoMessage() {}

func (x *GetAbastecimentoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAbastecimentoRequest.ProtoReflect.Descriptor instead.
func (*GetAbastecimentoRequest) Descriptor() ([]byte, []int) {
	return file_apps_posto_abastecimento_abastecimento_proto_rawDescGZIP(), []int{1}
}

func (x *GetAbastecimentoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAbastecimentoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Abastecimento *Abastecimento         `protobuf:"bytes,1,opt,name=abastecimento,proto3" json:"abastecimento,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAbastecimentoResponse) Reset() {
	*x = GetAbastecimentoResponse{}
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAbastecimentoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAbastecimentoResponse) ProtoMessage() {}

func (x *GetAbastecimentoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAbastecimentoResponse.ProtoReflect.Descriptor instead.
func (*GetAbastecimentoResponse) Descriptor() ([]byte, []int) {
	return file_apps_posto_abastecimento_abastecimento_proto_rawDescGZIP(), []int{2}
}

func (x *GetAbastecimentoResponse) GetAbastecimento() *Abastecimento {
	if x != nil {
		return x.Abastecimento
	}
	return nil
}

type ListAbastecimentoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter        *filter.Filter         `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAbastecimentoRequest) Reset() {
	*x = ListAbastecimentoRequest{}
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAbastecimentoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAbastecimentoRequest) ProtoMessage() {}

func (x *ListAbastecimentoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAbastecimentoRequest.ProtoReflect.Descriptor instead.
func (*ListAbastecimentoRequest) Descriptor() ([]byte, []int) {
	return file_apps_posto_abastecimento_abastecimento_proto_rawDescGZIP(), []int{3}
}

func (x *ListAbastecimentoRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ListAbastecimentoRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAbastecimentoRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListAbastecimentoRequest) GetFilter() *filter.Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListAbastecimentoResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AbastecimentoList []*Abastecimento       `protobuf:"bytes,1,rep,name=abastecimento_list,json=abastecimentoList,proto3" json:"abastecimento_list,omitempty"`
	NextPageToken     string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListAbastecimentoResponse) Reset() {
	*x = ListAbastecimentoResponse{}
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAbastecimentoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAbastecimentoResponse) ProtoMessage() {}

func (x *ListAbastecimentoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAbastecimentoResponse.ProtoReflect.Descriptor instead.
func (*ListAbastecimentoResponse) Descriptor() ([]byte, []int) {
	return file_apps_posto_abastecimento_abastecimento_proto_rawDescGZIP(), []int{4}
}

func (x *ListAbastecimentoResponse) GetAbastecimentoList() []*Abastecimento {
	if x != nil {
		return x.AbastecimentoList
	}
	return nil
}

func (x *ListAbastecimentoResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type RecebeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Marca          string                 `protobuf:"bytes,1,opt,name=marca,proto3" json:"marca,omitempty"`
	Abastecimentos []*Abastecimento       `protobuf:"bytes,2,rep,name=abastecimentos,proto3" json:"abastecimentos,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecebeRequest) Reset() {
	*x = RecebeRequest{}
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecebeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecebeRequest) ProtoMessage() {}

func (x *RecebeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecebeRequest.ProtoReflect.Descriptor instead.
func (*RecebeRequest) Descriptor() ([]byte, []int) {
	return file_apps_posto_abastecimento_abastecimento_proto_rawDescGZIP(), []int{5}
}

func (x *RecebeRequest) GetMarca() string {
	if x != nil {
		return x.Marca
	}
	return ""
}

func (x *RecebeRequest) GetAbastecimentos() []*Abastecimento {
	if x != nil {
		return x.Abastecimentos
	}
	return nil
}

type Recusa struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrigemId      string                 `protobuf:"bytes,1,opt,name=origem_id,json=origemId,proto3" json:"origem_id,omitempty"`
	Motivo        string                 `protobuf:"bytes,2,opt,name=motivo,proto3" json:"motivo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recusa) Reset() {
	*x = Recusa{}
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recusa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recusa) ProtoMessage() {}

func (x *Recusa) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recusa.ProtoReflect.Descriptor instead.
func (*Recusa) Descriptor() ([]byte, []int) {
	return file_apps_posto_abastecimento_abastecimento_proto_rawDescGZIP(), []int{6}
}

func (x *Recusa) GetOrigemId() string {
	if x != nil {
		return x.OrigemId
	}
	return ""
}

func (x *Recusa) GetMotivo() string {
	if x != nil {
		return x.Motivo
	}
	return ""
}

type RecebeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Origens que o sistema guardou (ou já tinha): a automação pode dar baixa nelas.
	Aceitos       []string  `protobuf:"bytes,1,rep,name=aceitos,proto3" json:"aceitos,omitempty"`
	Recusas       []*Recusa `protobuf:"bytes,2,rep,name=recusas,proto3" json:"recusas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecebeResponse) Reset() {
	*x = RecebeResponse{}
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecebeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecebeResponse) ProtoMessage() {}

func (x *RecebeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecebeResponse.ProtoReflect.Descriptor instead.
func (*RecebeResponse) Descriptor() ([]byte, []int) {
	return file_apps_posto_abastecimento_abastecimento_proto_rawDescGZIP(), []int{7}
}

func (x *RecebeResponse) GetAceitos() []string {
	if x != nil {
		return x.Aceitos
	}
	return nil
}

func (x *RecebeResponse) GetRecusas() []*Recusa {
	if x != nil {
		return x.Recusas
	}
	return nil
}

type ReservaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Pessoa do frentista identificado no caixa. Não substitui o frentista informado pela bomba.
	FrentistaId   string `protobuf:"bytes,2,opt,name=frentista_id,json=frentistaId,proto3" json:"frentista_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservaRequest) Reset() {
	*x = ReservaRequest{}
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservaRequest) ProtoMessage() {}

func (x *ReservaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservaRequest.ProtoReflect.Descriptor instead.
func (*ReservaRequest) Descriptor() ([]byte, []int) {
	return file_apps_posto_abastecimento_abastecimento_proto_rawDescGZIP(), []int{8}
}

func (x *ReservaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReservaRequest) GetFrentistaId() string {
	if x != nil {
		return x.FrentistaId
	}
	return ""
}

type ReservaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Abastecimento *Abastecimento         `protobuf:"bytes,1,opt,name=abastecimento,proto3" json:"abastecimento,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservaResponse) Reset() {
	*x = ReservaResponse{}
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservaResponse) ProtoMessage() {}

func (x *ReservaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservaResponse.ProtoReflect.Descriptor instead.
func (*ReservaResponse) Descriptor() ([]byte, []int) {
	return file_apps_posto_abastecimento_abastecimento_proto_rawDescGZIP(), []int{9}
}

func (x *ReservaResponse) GetAbastecimento() *Abastecimento {
	if x != nil {
		return x.Abastecimento
	}
	return nil
}

type AfericaoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AfericaoRequest) Reset() {
	*x = AfericaoRequest{}
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AfericaoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AfericaoRequest) ProtoMessage() {}

func (x *AfericaoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AfericaoRequest.ProtoReflect.Descriptor instead.
func (*AfericaoRequest) Descriptor() ([]byte, []int) {
	return file_apps_posto_abastecimento_abastecimento_proto_rawDescGZIP(), []int{10}
}

func (x *AfericaoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AfericaoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Abastecimento *Abastecimento         `protobuf:"bytes,1,opt,name=abastecimento,proto3" json:"abastecimento,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AfericaoResponse) Reset() {
	*x = AfericaoResponse{}
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AfericaoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AfericaoResponse) ProtoMessage() {}

func (x *AfericaoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AfericaoResponse.ProtoReflect.Descriptor instead.
func (*AfericaoResponse) Descriptor() ([]byte, []int) {
	return file_apps_posto_abastecimento_abastecimento_proto_rawDescGZIP(), []int{11}
}

func (x *AfericaoResponse) GetAbastecimento() *Abastecimento {
	if x != nil {
		return x.Abastecimento
	}
	return nil
}

type ResumoPorBicoRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DataHoraInicial *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=data_hora_inicial,json=dataHoraInicial,proto3" json:"data_hora_inicial,omitempty"`
	DataHoraFinal   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=data_hora_final,json=dataHoraFinal,proto3" json:"data_hora_final,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResumoPorBicoRequest) Reset() {
	*x = ResumoPorBicoRequest{}
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumoPorBicoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumoPorBicoRequest) ProtoMessage() {}

func (x *ResumoPorBicoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumoPorBicoRequest.ProtoReflect.Descriptor instead.
func (*ResumoPorBicoRequest) Descriptor() ([]byte, []int) {
	return file_apps_posto_abastecimento_abastecimento_proto_rawDescGZIP(), []int{12}
}

func (x *ResumoPorBicoRequest) GetDataHoraInicial() *timestamppb.Timestamp {
	if x != nil {
		return x.DataHoraInicial
	}
	return nil
}

func (x *ResumoPorBicoRequest) GetDataHoraFinal() *timestamppb.Timestamp {
	if x != nil {
		return x.DataHoraFinal
	}
	return nil
}

type Salto struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	DataHora                *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=data_hora,json=dataHora,proto3" json:"data_hora,omitempty"`
	EncerranteFinalAnterior float64                `protobuf:"fixed64,2,opt,name=encerrante_final_anterior,json=encerranteFinalAnterior,proto3" json:"encerrante_final_anterior,omitempty"`
	EncerranteInicial       float64                `protobuf:"fixed64,3,opt,name=encerrante_inicial,json=encerranteInicial,proto3" json:"encerrante_inicial,omitempty"`
	Litros                  float64                `protobuf:"fixed64,4,opt,name=litros,proto3" json:"litros,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Salto) Reset() {
	*x = Salto{}
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Salto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Salto) ProtoMessage() {}

func (x *Salto) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Salto.ProtoReflect.Descriptor instead.
func (*Salto) Descriptor() ([]byte, []int) {
	return file_apps_posto_abastecimento_abastecimento_proto_rawDescGZIP(), []int{13}
}

func (x *Salto) GetDataHora() *timestamppb.Timestamp {
	if x != nil {
		return x.DataHora
	}
	return nil
}

func (x *Salto) GetEncerranteFinalAnterior() float64 {
	if x != nil {
		return x.EncerranteFinalAnterior
	}
	return 0
}

func (x *Salto) GetEncerranteInicial() float64 {
	if x != nil {
		return x.EncerranteInicial
	}
	return 0
}

func (x *Salto) GetLitros() float64 {
	if x != nil {
		return x.Litros
	}
	return 0
}

type ResumoBico struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NumBico           int32                  `protobuf:"varint,1,opt,name=num_bico,json=numBico,proto3" json:"num_bico,omitempty"`
	NumBomba          string                 `protobuf:"bytes,2,opt,name=num_bomba,json=numBomba,proto3" json:"num_bomba,omitempty"`
	NumTanque         string                 `protobuf:"bytes,3,opt,name=num_tanque,json=numTanque,proto3" json:"num_tanque,omitempty"`
	ProdutoId         string                 `protobuf:"bytes,4,opt,name=produto_id,json=produtoId,proto3" json:"produto_id,omitempty"`
	ProdutoNome       string                 `protobuf:"bytes,5,opt,name=produto_nome,json=produtoNome,proto3" json:"produto_nome,omitempty"`
	EncerranteInicial float64                `protobuf:"fixed64,6,opt,name=encerrante_inicial,json=encerranteInicial,proto3" json:"encerrante_inicial,omitempty"`
	EncerranteFinal   float64                `protobuf:"fixed64,7,opt,name=encerrante_final,json=encerranteFinal,proto3" json:"encerrante_final,omitempty"`
	LitrosEncerrante  float64                `protobuf:"fixed64,8,opt,name=litros_encerrante,json=litrosEncerrante,proto3" json:"litros_encerrante,omitempty"`
	LitrosVendidos    float64                `protobuf:"fixed64,9,opt,name=litros_vendidos,json=litrosVendidos,proto3" json:"litros_vendidos,omitempty"`
	LitrosAfericao    float64                `protobuf:"fixed64,10,opt,name=litros_afericao,json=litrosAfericao,proto3" json:"litros_afericao,omitempty"`
	LitrosPendentes   float64                `protobuf:"fixed64,11,opt,name=litros_pendentes,json=litrosPendentes,proto3" json:"litros_pendentes,omitempty"`
	LitrosEmVenda     float64                `protobuf:"fixed64,12,opt,name=litros_em_venda,json=litrosEmVenda,proto3" json:"litros_em_venda,omitempty"`
	Diferenca         float64                `protobuf:"fixed64,13,opt,name=diferenca,proto3" json:"diferenca,omitempty"`
	ValorVendido      float64                `protobuf:"fixed64,14,opt,name=valor_vendido,json=valorVendido,proto3" json:"valor_vendido,omitempty"`
	Quantidade        int32                  `protobuf:"varint,15,opt,name=quantidade,proto3" json:"quantidade,omitempty"`
	Saltos            []*Salto               `protobuf:"bytes,16,rep,name=saltos,proto3" json:"saltos,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResumoBico) Reset() {
	*x = ResumoBico{}
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumoBico) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumoBico) ProtoMessage() {}

func (x *ResumoBico) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumoBico.ProtoReflect.Descriptor instead.
func (*ResumoBico) Descriptor() ([]byte, []int) {
	return file_apps_posto_abastecimento_abastecimento_proto_rawDescGZIP(), []int{14}
}

func (x *ResumoBico) GetNumBico() int32 {
	if x != nil {
		return x.NumBico
	}
	return 0
}

func (x *ResumoBico) GetNumBomba() string {
	if x != nil {
		return x.NumBomba
	}
	return ""
}

func (x *ResumoBico) GetNumTanque() string {
	if x != nil {
		return x.NumTanque
	}
	return ""
}

func (x *ResumoBico) GetProdutoId() string {
	if x != nil {
		return x.ProdutoId
	}
	return ""
}

func (x *ResumoBico) GetProdutoNome() string {
	if x != nil {
		return x.ProdutoNome
	}
	return ""
}

func (x *ResumoBico) GetEncerranteInicial() float64 {
	if x != nil {
		return x.EncerranteInicial
	}
	return 0
}

func (x *ResumoBico) GetEncerranteFinal() float64 {
	if x != nil {
		return x.EncerranteFinal
	}
	return 0
}

func (x *ResumoBico) GetLitrosEncerrante() float64 {
	if x != nil {
		return x.LitrosEncerrante
	}
	return 0
}

func (x *ResumoBico) GetLitrosVendidos() float64 {
	if x != nil {
		return x.LitrosVendidos
	}
	return 0
}

func (x *ResumoBico) GetLitrosAfericao() float64 {
	if x != nil {
		return x.LitrosAfericao
	}
	return 0
}

func (x *ResumoBico) GetLitrosPendentes() float64 {
	if x != nil {
		return x.LitrosPendentes
	}
	return 0
}

func (x *ResumoBico) GetLitrosEmVenda() float64 {
	if x != nil {
		return x.LitrosEmVenda
	}
	return 0
}

func (x *ResumoBico) GetDiferenca() float64 {
	if x != nil {
		return x.Diferenca
	}
	return 0
}

func (x *ResumoBico) GetValorVendido() float64 {
	if x != nil {
		return x.ValorVendido
	}
	return 0
}

func (x *ResumoBico) GetQuantidade() int32 {
	if x != nil {
		return x.Quantidade
	}
	return 0
}

func (x *ResumoBico) GetSaltos() []*Salto {
	if x != nil {
		return x.Saltos
	}
	return nil
}

type ResumoPorBicoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bicos         []*ResumoBico          `protobuf:"bytes,1,rep,name=bicos,proto3" json:"bicos,omitempty"`
	Avisos        []string               `protobuf:"bytes,2,rep,name=avisos,proto3" json:"avisos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumoPorBicoResponse) Reset() {
	*x = ResumoPorBicoResponse{}
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumoPorBicoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumoPorBicoResponse) ProtoMessage() {}

func (x *ResumoPorBicoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_abastecimento_abastecimento_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumoPorBicoResponse.ProtoReflect.Descriptor instead.
func (*ResumoPorBicoResponse) Descriptor() ([]byte, []int) {
	return file_apps_posto_abastecimento_abastecimento_proto_rawDescGZIP(), []int{15}
}

func (x *ResumoPorBicoResponse) GetBicos() []*ResumoBico {
	if x != nil {
		return x.Bicos
	}
	return nil
}

func (x *ResumoPorBicoResponse) GetAvisos() []string {
	if x != nil {
		return x.Avisos
	}
	return nil
}

var File_apps_posto_abastecimento_abastecimento_proto protoreflect.FileDescriptor

const file_apps_posto_abastecimento_abastecimento_proto_rawDesc = "" +
	"\n" +
	",apps/posto/abastecimento/abastecimento.proto\x12\rabastecimento\x1a\x1cgoogle/api/annotations.proto\x1a\x1fplugins/validate/validate.proto\x1a\x1dplugins/service/service.proto\x1a\x13filter/filter.proto\x1a\x1ecommon/metadata/metadata.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbc\n" +
	"\n" +
	"\rAbastecimento\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x04 \x01(\tR\buserName\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\tR\x02id\x12-\n" +
	"\x06fields\x18\x06 \x01(\v2\x15.metadata.BasicFieldsR\x06fields\x12$\n" +
	"\torigem_id\x18\a \x01(\tB\a\xfaB\x04r\x02\x18xR\borigemId\x12\x14\n" +
	"\x05marca\x18\b \x01(\tR\x05marca\x12\x19\n" +
	"\bnum_bico\x18\t \x01(\x05R\anumBico\x12\x1b\n" +
	"\tnum_bomba\x18\n" +
	" \x01(\tR\bnumBomba\x12\x1d\n" +
	"\n" +
	"num_tanque\x18\v \x01(\tR\tnumTanque\x12\x1d\n" +
	"\n" +
	"produto_id\x18\f \x01(\tR\tprodutoId\x12!\n" +
	"\fproduto_nome\x18\r \x01(\tR\vprodutoNome\x12\x1d\n" +
	"\n" +
	"codigo_anp\x18\x0e \x01(\tR\tcodigoAnp\x12\x16\n" +
	"\x06volume\x18\x0f \x01(\x01R\x06volume\x12%\n" +
	"\x0epreco_unitario\x18\x10 \x01(\x01R\rprecoUnitario\x12\x1f\n" +
	"\vvalor_total\x18\x11 \x01(\x01R\n" +
	"valorTotal\x12-\n" +
	"\x12encerrante_inicial\x18\x12 \x01(\x01R\x11encerranteInicial\x12)\n" +
	"\x10encerrante_final\x18\x13 \x01(\x01R\x0fencerranteFinal\x127\n" +
	"\tdata_hora\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\bdataHora\x123\n" +
	"\bsituacao\x18\x15 \x01(\x0e2\x17.abastecimento.SituacaoR\bsituacao\x12'\n" +
	"\x04tipo\x18\x16 \x01(\x0e2\x13.abastecimento.TipoR\x04tipo\x12\x1b\n" +
	"\tpedido_id\x18\x17 \x01(\tR\bpedidoId\x12#\n" +
	"\rpedido_numero\x18\x18 \x01(\x05R\fpedidoNumero\x12&\n" +
	"\x0freserva_user_id\x18\x19 \x01(\tR\rreservaUserId\x12*\n" +
	"\x11reserva_user_name\x18\x1a \x01(\tR\x0freservaUserName\x129\n" +
	"\n" +
	"reserva_em\x18\x1b \x01(\v2\x1a.google.protobuf.TimestampR\treservaEm\x12\x1a\n" +
	"\bbloqueio\x18\x1c \x01(\tR\bbloqueio\x122\n" +
	"\x10frentista_codigo\x18\x1d \x01(\tB\a\xfaB\x04r\x02\x18<R\x0ffrentistaCodigo\x12!\n" +
	"\ffrentista_id\x18\x1e \x01(\tR\vfrentistaId\x12%\n" +
	"\x0efrentista_nome\x18\x1f \x01(\tR\rfrentistaNome\x12\x1f\n" +
	"\vnivel_preco\x18  \x01(\x05R\n" +
	"nivelPreco\x12\x1f\n" +
	"\vveiculo_tag\x18! \x01(\tR\n" +
	"veiculoTag\x12(\n" +
	"\x10posto_veiculo_id\x18\" \x01(\tR\x0epostoVeiculoId\x12\x1f\n" +
	"\vposto_placa\x18# \x01(\tR\n" +
	"postoPlaca:\x03\xc0>\x01\")\n" +
	"\x17GetAbastecimentoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"^\n" +
	"\x18GetAbastecimentoResponse\x12B\n" +
	"\rabastecimento\x18\x01 \x01(\v2\x1c.abastecimento.AbastecimentoR\rabastecimento\"\x89\x01\n" +
	"\x18ListAbastecimentoRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x1f\n" +
	"\x06filter\x18\x05 \x01(\v2\a.FilterR\x06filter\"\x90\x01\n" +
	"\x19ListAbastecimentoResponse\x12K\n" +
	"\x12abastecimento_list\x18\x01 \x03(\v2\x1c.abastecimento.AbastecimentoR\x11abastecimentoList\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"k\n" +
	"\rRecebeRequest\x12\x14\n" +
	"\x05marca\x18\x01 \x01(\tR\x05marca\x12D\n" +
	"\x0eabastecimentos\x18\x02 \x03(\v2\x1c.abastecimento.AbastecimentoR\x0eabastecimentos\"=\n" +
	"\x06Recusa\x12\x1b\n" +
	"\torigem_id\x18\x01 \x01(\tR\borigemId\x12\x16\n" +
	"\x06motivo\x18\x02 \x01(\tR\x06motivo\"[\n" +
	"\x0eRecebeResponse\x12\x18\n" +
	"\aaceitos\x18\x01 \x03(\tR\aaceitos\x12/\n" +
	"\arecusas\x18\x02 \x03(\v2\x15.abastecimento.RecusaR\arecusas\"C\n" +
	"\x0eReservaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\ffrentista_id\x18\x02 \x01(\tR\vfrentistaId\"U\n" +
	"\x0fReservaResponse\x12B\n" +
	"\rabastecimento\x18\x01 \x01(\v2\x1c.abastecimento.AbastecimentoR\rabastecimento\"!\n" +
	"\x0fAfericaoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"V\n" +
	"\x10AfericaoResponse\x12B\n" +
	"\rabastecimento\x18\x01 \x01(\v2\x1c.abastecimento.AbastecimentoR\rabastecimento\"\xa2\x01\n" +
	"\x14ResumoPorBicoRequest\x12F\n" +
	"\x11data_hora_inicial\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x0fdataHoraInicial\x12B\n" +
	"\x0fdata_hora_final\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\rdataHoraFinal\"\xc3\x01\n" +
	"\x05Salto\x127\n" +
	"\tdata_hora\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bdataHora\x12:\n" +
	"\x19encerrante_final_anterior\x18\x02 \x01(\x01R\x17encerranteFinalAnterior\x12-\n" +
	"\x12encerrante_inicial\x18\x03 \x01(\x01R\x11encerranteInicial\x12\x16\n" +
	"\x06litros\x18\x04 \x01(\x01R\x06litros\"\xe2\x04\n" +
	"\n" +
	"ResumoBico\x12\x19\n" +
	"\bnum_bico\x18\x01 \x01(\x05R\anumBico\x12\x1b\n" +
	"\tnum_bomba\x18\x02 \x01(\tR\bnumBomba\x12\x1d\n" +
	"\n" +
	"num_tanque\x18\x03 \x01(\tR\tnumTanque\x12\x1d\n" +
	"\n" +
	"produto_id\x18\x04 \x01(\tR\tprodutoId\x12!\n" +
	"\fproduto_nome\x18\x05 \x01(\tR\vprodutoNome\x12-\n" +
	"\x12encerrante_inicial\x18\x06 \x01(\x01R\x11encerranteInicial\x12)\n" +
	"\x10encerrante_final\x18\a \x01(\x01R\x0fencerranteFinal\x12+\n" +
	"\x11litros_encerrante\x18\b \x01(\x01R\x10litrosEncerrante\x12'\n" +
	"\x0flitros_vendidos\x18\t \x01(\x01R\x0elitrosVendidos\x12'\n" +
	"\x0flitros_afericao\x18\n" +
	" \x01(\x01R\x0elitrosAfericao\x12)\n" +
	"\x10litros_pendentes\x18\v \x01(\x01R\x0flitrosPendentes\x12&\n" +
	"\x0flitros_em_venda\x18\f \x01(\x01R\rlitrosEmVenda\x12\x1c\n" +
	"\tdiferenca\x18\r \x01(\x01R\tdiferenca\x12#\n" +
	"\rvalor_vendido\x18\x0e \x01(\x01R\fvalorVendido\x12\x1e\n" +
	"\n" +
	"quantidade\x18\x0f \x01(\x05R\n" +
	"quantidade\x12,\n" +
	"\x06saltos\x18\x10 \x03(\v2\x14.abastecimento.SaltoR\x06saltos\"`\n" +
	"\x15ResumoPorBicoResponse\x12/\n" +
	"\x05bicos\x18\x01 \x03(\v2\x19.abastecimento.ResumoBicoR\x05bicos\x12\x16\n" +
	"\x06avisos\x18\x02 \x03(\tR\x06avisos*\x7f\n" +
	"\bSituacao\x12\x18\n" +
	"\x14SITUACAO_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SITUACAO_PENDENTE\x10\x01\x12\x15\n" +
	"\x11SITUACAO_EM_VENDA\x10\x02\x12\x14\n" +
	"\x10SITUACAO_VENDIDO\x10\x03\x12\x15\n" +
	"\x11SITUACAO_AFERICAO\x10\x04*R\n" +
	"\x04Tipo\x12\x14\n" +
	"\x10TIPO_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vTIPO_NORMAL\x10\x01\x12\x11\n" +
	"\rTIPO_AFERICAO\x10\x02\x12\x10\n" +
	"\fTIPO_OFFLINE\x10\x032\xa2\x06\n" +
	"\x14AbastecimentoService\x12~\n" +
	"\x03Get\x12&.abastecimento.GetAbastecimentoRequest\x1a'.abastecimento.GetAbastecimentoResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/posto/abastecimentos/{id}\x12\x84\x01\n" +
	"\x04List\x12'.abastecimento.ListAbastecimentoRequest\x1a(.abastecimento.ListAbastecimentoResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/api/posto/abastecimentos/list\x12r\n" +
	"\x06Recebe\x12\x1c.abastecimento.RecebeRequest\x1a\x1d.abastecimento.RecebeResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/posto/abastecimentos/recebe\x12{\n" +
	"\aReserva\x12\x1d.abastecimento.ReservaRequest\x1a\x1e.abastecimento.ReservaResponse\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/api/posto/abastecimentos/{id}/reserva\x12\x7f\n" +
	"\bAfericao\x12\x1e.abastecimento.AfericaoRequest\x1a\x1f.abastecimento.AfericaoResponse\"2\x82\xd3\xe4\x93\x02,:\x01*\"'/api/posto/abastecimentos/{id}/afericao\x12\x90\x01\n" +
	"\rResumoPorBico\x12#.abastecimento.ResumoPorBicoRequest\x1a$.abastecimento.ResumoPorBicoResponse\"4\x82\xd3\xe4\x93\x02.:\x01*\")/api/posto/abastecimentos/resumo-por-bicoB\xb8\x01\n" +
	"\x11com.abastecimentoB\x12AbastecimentoProtoP\x01Z;github.com/linksoft-dev/sdks/go/pb/apps/posto/abastecimento\xa2\x02\x03AXX\xaa\x02\rAbastecimento\xca\x02\rAbastecimento\xe2\x02\x19Abastecimento\\GPBMetadata\xea\x02\rAbastecimentob\x06proto3"

var (
	file_apps_posto_abastecimento_abastecimento_proto_rawDescOnce sync.Once
	file_apps_posto_abastecimento_abastecimento_proto_rawDescData []byte
)

func file_apps_posto_abastecimento_abastecimento_proto_rawDescGZIP() []byte {
	file_apps_posto_abastecimento_abastecimento_proto_rawDescOnce.Do(func() {
		file_apps_posto_abastecimento_abastecimento_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_posto_abastecimento_abastecimento_proto_rawDesc), len(file_apps_posto_abastecimento_abastecimento_proto_rawDesc)))
	})
	return file_apps_posto_abastecimento_abastecimento_proto_rawDescData
}

var file_apps_posto_abastecimento_abastecimento_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_apps_posto_abastecimento_abastecimento_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_apps_posto_abastecimento_abastecimento_proto_goTypes = []any{
	(Situacao)(0),                     // 0: abastecimento.Situacao
	(Tipo)(0),                         // 1: abastecimento.Tipo
	(*Abastecimento)(nil),             // 2: abastecimento.Abastecimento
	(*GetAbastecimentoRequest)(nil),   // 3: abastecimento.GetAbastecimentoRequest
	(*GetAbastecimentoResponse)(nil),  // 4: abastecimento.GetAbastecimentoResponse
	(*ListAbastecimentoRequest)(nil),  // 5: abastecimento.ListAbastecimentoRequest
	(*ListAbastecimentoResponse)(nil), // 6: abastecimento.ListAbastecimentoResponse
	(*RecebeRequest)(nil),             // 7: abastecimento.RecebeRequest
	(*Recusa)(nil),                    // 8: abastecimento.Recusa
	(*RecebeResponse)(nil),            // 9: abastecimento.RecebeResponse
	(*ReservaRequest)(nil),            // 10: abastecimento.ReservaRequest
	(*ReservaResponse)(nil),           // 11: abastecimento.ReservaResponse
	(*AfericaoRequest)(nil),           // 12: abastecimento.AfericaoRequest
	(*AfericaoResponse)(nil),          // 13: abastecimento.AfericaoResponse
	(*ResumoPorBicoRequest)(nil),      // 14: abastecimento.ResumoPorBicoRequest
	(*Salto)(nil),                     // 15: abastecimento.Salto
	(*ResumoBico)(nil),                // 16: abastecimento.ResumoBico
	(*ResumoPorBicoResponse)(nil),     // 17: abastecimento.ResumoPorBicoResponse
	(*timestamppb.Timestamp)(nil),     // 18: google.protobuf.Timestamp
	(*metadata.BasicFields)(nil),      // 19: metadata.BasicFields
	(*filter.Filter)(nil),             // 20: Filter
}
var file_apps_posto_abastecimento_abastecimento_proto_depIdxs = []int32{
	18, // 0: abastecimento.Abastecimento.created_at:type_name -> google.protobuf.Timestamp
	18, // 1: abastecimento.Abastecimento.updated_at:type_name -> google.protobuf.Timestamp
	19, // 2: abastecimento.Abastecimento.fields:type_name -> metadata.BasicFields
	18, // 3: abastecimento.Abastecimento.data_hora:type_name -> google.protobuf.Timestamp
	0,  // 4: abastecimento.Abastecimento.situacao:type_name -> abastecimento.Situacao
	1,  // 5: abastecimento.Abastecimento.tipo:type_name -> abastecimento.Tipo
	18, // 6: abastecimento.Abastecimento.reserva_em:type_name -> google.protobuf.Timestamp
	2,  // 7: abastecimento.GetAbastecimentoResponse.abastecimento:type_name -> abastecimento.Abastecimento
	20, // 8: abastecimento.ListAbastecimentoRequest.filter:type_name -> Filter
	2,  // 9: abastecimento.ListAbastecimentoResponse.abastecimento_list:type_name -> abastecimento.Abastecimento
	2,  // 10: abastecimento.RecebeRequest.abastecimentos:type_name -> abastecimento.Abastecimento
	8,  // 11: abastecimento.RecebeResponse.recusas:type_name -> abastecimento.Recusa
	2,  // 12: abastecimento.ReservaResponse.abastecimento:type_name -> abastecimento.Abastecimento
	2,  // 13: abastecimento.AfericaoResponse.abastecimento:type_name -> abastecimento.Abastecimento
	18, // 14: abastecimento.ResumoPorBicoRequest.data_hora_inicial:type_name -> google.protobuf.Timestamp
	18, // 15: abastecimento.ResumoPorBicoRequest.data_hora_final:type_name -> google.protobuf.Timestamp
	18, // 16: abastecimento.Salto.data_hora:type_name -> google.protobuf.Timestamp
	15, // 17: abastecimento.ResumoBico.saltos:type_name -> abastecimento.Salto
	16, // 18: abastecimento.ResumoPorBicoResponse.bicos:type_name -> abastecimento.ResumoBico
	3,  // 19: abastecimento.AbastecimentoService.Get:input_type -> abastecimento.GetAbastecimentoRequest
	5,  // 20: abastecimento.AbastecimentoService.List:input_type -> abastecimento.ListAbastecimentoRequest
	7,  // 21: abastecimento.AbastecimentoService.Recebe:input_type -> abastecimento.RecebeRequest
	10, // 22: abastecimento.AbastecimentoService.Reserva:input_type -> abastecimento.ReservaRequest
	12, // 23: abastecimento.AbastecimentoService.Afericao:input_type -> abastecimento.AfericaoRequest
	14, // 24: abastecimento.AbastecimentoService.ResumoPorBico:input_type -> abastecimento.ResumoPorBicoRequest
	4,  // 25: abastecimento.AbastecimentoService.Get:output_type -> abastecimento.GetAbastecimentoResponse
	6,  // 26: abastecimento.AbastecimentoService.List:output_type -> abastecimento.ListAbastecimentoResponse
	9,  // 27: abastecimento.AbastecimentoService.Recebe:output_type -> abastecimento.RecebeResponse
	11, // 28: abastecimento.AbastecimentoService.Reserva:output_type -> abastecimento.ReservaResponse
	13, // 29: abastecimento.AbastecimentoService.Afericao:output_type -> abastecimento.AfericaoResponse
	17, // 30: abastecimento.AbastecimentoService.ResumoPorBico:output_type -> abastecimento.ResumoPorBicoResponse
	25, // [25:31] is the sub-list for method output_type
	19, // [19:25] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_apps_posto_abastecimento_abastecimento_proto_init() }
func file_apps_posto_abastecimento_abastecimento_proto_init() {
	if File_apps_posto_abastecimento_abastecimento_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_posto_abastecimento_abastecimento_proto_rawDesc), len(file_apps_posto_abastecimento_abastecimento_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_posto_abastecimento_abastecimento_proto_goTypes,
		DependencyIndexes: file_apps_posto_abastecimento_abastecimento_proto_depIdxs,
		EnumInfos:         file_apps_posto_abastecimento_abastecimento_proto_enumTypes,
		MessageInfos:      file_apps_posto_abastecimento_abastecimento_proto_msgTypes,
	}.Build()
	File_apps_posto_abastecimento_abastecimento_proto = out.File
	file_apps_posto_abastecimento_abastecimento_proto_goTypes = nil
	file_apps_posto_abastecimento_abastecimento_proto_depIdxs = nil
}
