// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: apps/estoque/movimento/movimentoestoque.proto

package movimento

import (
	metadata "github.com/linksoft-dev/sdks/go/pb/common/metadata"
	_ "github.com/linksoft-dev/sdks/go/pb/plugins/service"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MovimentoEstoque struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=createdAt,proto3" json:"createdAt,omitempty"` // Data de criação
	Id                   string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Fields               *metadata.BasicFields  `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
	UserId               string                 `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"` // ID do usuário que realizou a ação
	UserName             string                 `protobuf:"bytes,5,opt,name=userName,proto3" json:"userName,omitempty"`
	EstoqueNome          string                 `protobuf:"bytes,6,opt,name=estoqueNome,proto3" json:"estoqueNome,omitempty"`
	ProdutoId            string                 `protobuf:"bytes,7,opt,name=produtoId,proto3" json:"produtoId,omitempty"`
	Tipo                 string                 `protobuf:"bytes,8,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Quantidade           float64                `protobuf:"fixed64,9,opt,name=quantidade,proto3" json:"quantidade,omitempty"`
	ValorUnitario        float64                `protobuf:"fixed64,10,opt,name=valorUnitario,proto3" json:"valorUnitario,omitempty"`
	Origem               string                 `protobuf:"bytes,11,opt,name=origem,proto3" json:"origem,omitempty"`
	OrigemId             string                 `protobuf:"bytes,12,opt,name=origemId,proto3" json:"origemId,omitempty"`
	OrigemNumero         string                 `protobuf:"bytes,13,opt,name=origemNumero,proto3" json:"origemNumero,omitempty"`
	Obs                  string                 `protobuf:"bytes,14,opt,name=obs,proto3" json:"obs,omitempty"`
	PessoaId             string                 `protobuf:"bytes,15,opt,name=pessoaId,proto3" json:"pessoaId,omitempty"`
	PessoaNome           string                 `protobuf:"bytes,16,opt,name=pessoaNome,proto3" json:"pessoaNome,omitempty"`
	ProdutoNome          string                 `protobuf:"bytes,17,opt,name=produtoNome,proto3" json:"produtoNome,omitempty"`
	QAnterior            float64                `protobuf:"fixed64,18,opt,name=qAnterior,proto3" json:"qAnterior,omitempty"`
	QAtual               float64                `protobuf:"fixed64,19,opt,name=qAtual,proto3" json:"qAtual,omitempty"`
	VariationId          string                 `protobuf:"bytes,20,opt,name=variation_id,json=variationId,proto3" json:"variation_id,omitempty"`                              // ID da variação movimentada
	VariationSku         string                 `protobuf:"bytes,21,opt,name=variation_sku,json=variationSku,proto3" json:"variation_sku,omitempty"`                           // SKU da variação (denormalizado)
	VariationDisplayName string                 `protobuf:"bytes,22,opt,name=variation_display_name,json=variationDisplayName,proto3" json:"variation_display_name,omitempty"` // Nome da variação (denormalizado)
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MovimentoEstoque) Reset() {
	*x = MovimentoEstoque{}
	mi := &file_apps_estoque_movimento_movimentoestoque_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovimentoEstoque) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovimentoEstoque) ProtoMessage() {}

func (x *MovimentoEstoque) ProtoReflect() protoreflect.Message {
	mi := &file_apps_estoque_movimento_movimentoestoque_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovimentoEstoque.ProtoReflect.Descriptor instead.
func (*MovimentoEstoque) Descriptor() ([]byte, []int) {
	return file_apps_estoque_movimento_movimentoestoque_proto_rawDescGZIP(), []int{0}
}

func (x *MovimentoEstoque) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MovimentoEstoque) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MovimentoEstoque) GetFields() *metadata.BasicFields {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *MovimentoEstoque) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MovimentoEstoque) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *MovimentoEstoque) GetEstoqueNome() string {
	if x != nil {
		return x.EstoqueNome
	}
	return ""
}

func (x *MovimentoEstoque) GetProdutoId() string {
	if x != nil {
		return x.ProdutoId
	}
	return ""
}

func (x *MovimentoEstoque) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *MovimentoEstoque) GetQuantidade() float64 {
	if x != nil {
		return x.Quantidade
	}
	return 0
}

func (x *MovimentoEstoque) GetValorUnitario() float64 {
	if x != nil {
		return x.ValorUnitario
	}
	return 0
}

func (x *MovimentoEstoque) GetOrigem() string {
	if x != nil {
		return x.Origem
	}
	return ""
}

func (x *MovimentoEstoque) GetOrigemId() string {
	if x != nil {
		return x.OrigemId
	}
	return ""
}

func (x *MovimentoEstoque) GetOrigemNumero() string {
	if x != nil {
		return x.OrigemNumero
	}
	return ""
}

func (x *MovimentoEstoque) GetObs() string {
	if x != nil {
		return x.Obs
	}
	return ""
}

func (x *MovimentoEstoque) GetPessoaId() string {
	if x != nil {
		return x.PessoaId
	}
	return ""
}

func (x *MovimentoEstoque) GetPessoaNome() string {
	if x != nil {
		return x.PessoaNome
	}
	return ""
}

func (x *MovimentoEstoque) GetProdutoNome() string {
	if x != nil {
		return x.ProdutoNome
	}
	return ""
}

func (x *MovimentoEstoque) GetQAnterior() float64 {
	if x != nil {
		return x.QAnterior
	}
	return 0
}

func (x *MovimentoEstoque) GetQAtual() float64 {
	if x != nil {
		return x.QAtual
	}
	return 0
}

func (x *MovimentoEstoque) GetVariationId() string {
	if x != nil {
		return x.VariationId
	}
	return ""
}

func (x *MovimentoEstoque) GetVariationSku() string {
	if x != nil {
		return x.VariationSku
	}
	return ""
}

func (x *MovimentoEstoque) GetVariationDisplayName() string {
	if x != nil {
		return x.VariationDisplayName
	}
	return ""
}

var File_apps_estoque_movimento_movimentoestoque_proto protoreflect.FileDescriptor

const file_apps_estoque_movimento_movimentoestoque_proto_rawDesc = "" +
	"\n" +
	"-apps/estoque/movimento/movimentoestoque.proto\x12\x10movimentoestoque\x1a\x1dplugins/service/service.proto\x1a\x1ecommon/metadata/metadata.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe8\x05\n" +
	"\x10MovimentoEstoque\x128\n" +
	"\tcreatedAt\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12-\n" +
	"\x06fields\x18\x03 \x01(\v2\x15.metadata.BasicFieldsR\x06fields\x12\x16\n" +
	"\x06userId\x18\x04 \x01(\tR\x06userId\x12\x1a\n" +
	"\buserName\x18\x05 \x01(\tR\buserName\x12+\n" +
	"\vestoqueNome\x18\x06 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18<R\vestoqueNome\x12\x1c\n" +
	"\tprodutoId\x18\a \x01(\tR\tprodutoId\x12\x12\n" +
	"\x04tipo\x18\b \x01(\tR\x04tipo\x12\x1e\n" +
	"\n" +
	"quantidade\x18\t \x01(\x01R\n" +
	"quantidade\x12$\n" +
	"\rvalorUnitario\x18\n" +
	" \x01(\x01R\rvalorUnitario\x12\x16\n" +
	"\x06origem\x18\v \x01(\tR\x06origem\x12\x1a\n" +
	"\borigemId\x18\f \x01(\tR\borigemId\x12\"\n" +
	"\forigemNumero\x18\r \x01(\tR\forigemNumero\x12\x10\n" +
	"\x03obs\x18\x0e \x01(\tR\x03obs\x12\x1a\n" +
	"\bpessoaId\x18\x0f \x01(\tR\bpessoaId\x12\x1e\n" +
	"\n" +
	"pessoaNome\x18\x10 \x01(\tR\n" +
	"pessoaNome\x12 \n" +
	"\vprodutoNome\x18\x11 \x01(\tR\vprodutoNome\x12\x1c\n" +
	"\tqAnterior\x18\x12 \x01(\x01R\tqAnterior\x12\x16\n" +
	"\x06qAtual\x18\x13 \x01(\x01R\x06qAtual\x12!\n" +
	"\fvariation_id\x18\x14 \x01(\tR\vvariationId\x12#\n" +
	"\rvariation_sku\x18\x15 \x01(\tR\fvariationSku\x124\n" +
	"\x16variation_display_name\x18\x16 \x01(\tR\x14variationDisplayName:\x06\xc0>\x01\xd0>\x01B\xc8\x01\n" +
	"\x14com.movimentoestoqueB\x15MovimentoestoqueProtoP\x01Z9github.com/linksoft-dev/sdks/go/pb/apps/estoque/movimento\xa2\x02\x03MXX\xaa\x02\x10Movimentoestoque\xca\x02\x10Movimentoestoque\xe2\x02\x1cMovimentoestoque\\GPBMetadata\xea\x02\x10Movimentoestoqueb\x06proto3"

var (
	file_apps_estoque_movimento_movimentoestoque_proto_rawDescOnce sync.Once
	file_apps_estoque_movimento_movimentoestoque_proto_rawDescData []byte
)

func file_apps_estoque_movimento_movimentoestoque_proto_rawDescGZIP() []byte {
	file_apps_estoque_movimento_movimentoestoque_proto_rawDescOnce.Do(func() {
		file_apps_estoque_movimento_movimentoestoque_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_estoque_movimento_movimentoestoque_proto_rawDesc), len(file_apps_estoque_movimento_movimentoestoque_proto_rawDesc)))
	})
	return file_apps_estoque_movimento_movimentoestoque_proto_rawDescData
}

var file_apps_estoque_movimento_movimentoestoque_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_apps_estoque_movimento_movimentoestoque_proto_goTypes = []any{
	(*MovimentoEstoque)(nil),      // 0: movimentoestoque.MovimentoEstoque
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*metadata.BasicFields)(nil),  // 2: metadata.BasicFields
}
var file_apps_estoque_movimento_movimentoestoque_proto_depIdxs = []int32{
	1, // 0: movimentoestoque.MovimentoEstoque.createdAt:type_name -> google.protobuf.Timestamp
	2, // 1: movimentoestoque.MovimentoEstoque.fields:type_name -> metadata.BasicFields
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_apps_estoque_movimento_movimentoestoque_proto_init() }
func file_apps_estoque_movimento_movimentoestoque_proto_init() {
	if File_apps_estoque_movimento_movimentoestoque_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_estoque_movimento_movimentoestoque_proto_rawDesc), len(file_apps_estoque_movimento_movimentoestoque_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apps_estoque_movimento_movimentoestoque_proto_goTypes,
		DependencyIndexes: file_apps_estoque_movimento_movimentoestoque_proto_depIdxs,
		MessageInfos:      file_apps_estoque_movimento_movimentoestoque_proto_msgTypes,
	}.Build()
	File_apps_estoque_movimento_movimentoestoque_proto = out.File
	file_apps_estoque_movimento_movimentoestoque_proto_goTypes = nil
	file_apps_estoque_movimento_movimentoestoque_proto_depIdxs = nil
}
