// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: apps/posto/medicao/medicao.proto

package medicao

import (
	metadata "github.com/linksoft-dev/sdks/go/pb/common/metadata"
	filter "github.com/linksoft-dev/sdks/go/pb/filter"
	_ "github.com/linksoft-dev/sdks/go/pb/plugins/service"
	_ "github.com/linksoft-dev/sdks/go/pb/plugins/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Origem int32

const (
	Origem_ORIGEM_UNSPECIFIED Origem = 0
	Origem_ORIGEM_MANUAL      Origem = 1
	Origem_ORIGEM_AUTOMATICA  Origem = 2
)

// Enum value maps for Origem.
var (
	Origem_name = map[int32]string{
		0: "ORIGEM_UNSPECIFIED",
		1: "ORIGEM_MANUAL",
		2: "ORIGEM_AUTOMATICA",
	}
	Origem_value = map[string]int32{
		"ORIGEM_UNSPECIFIED": 0,
		"ORIGEM_MANUAL":      1,
		"ORIGEM_AUTOMATICA":  2,
	}
)

func (x Origem) Enum() *Origem {
	p := new(Origem)
	*p = x
	return p
}

func (x Origem) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Origem) Descriptor() protoreflect.EnumDescriptor {
	return file_apps_posto_medicao_medicao_proto_enumTypes[0].Descriptor()
}

func (Origem) Type() protoreflect.EnumType {
	return &file_apps_posto_medicao_medicao_proto_enumTypes[0]
}

func (x Origem) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Origem.Descriptor instead.
func (Origem) EnumDescriptor() ([]byte, []int) {
	return file_apps_posto_medicao_medicao_proto_rawDescGZIP(), []int{0}
}

type Medicao struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UserId       string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName     string                 `protobuf:"bytes,4,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Id           string                 `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	Fields       *metadata.BasicFields  `protobuf:"bytes,6,opt,name=fields,proto3" json:"fields,omitempty"`
	TanqueId     string                 `protobuf:"bytes,7,opt,name=tanque_id,json=tanqueId,proto3" json:"tanque_id,omitempty"`
	TanqueNumero int32                  `protobuf:"varint,8,opt,name=tanque_numero,json=tanqueNumero,proto3" json:"tanque_numero,omitempty"`
	ProdutoId    string                 `protobuf:"bytes,9,opt,name=produto_id,json=produtoId,proto3" json:"produto_id,omitempty"`
	ProdutoNome  string                 `protobuf:"bytes,10,opt,name=produto_nome,json=produtoNome,proto3" json:"produto_nome,omitempty"`
	DataHora     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=data_hora,json=dataHora,proto3" json:"data_hora,omitempty"`
	// Litros de produto.
	Volume float64 `protobuf:"fixed64,12,opt,name=volume,proto3" json:"volume,omitempty"`
	// Litros de água no fundo do tanque.
	Agua        float64 `protobuf:"fixed64,13,opt,name=agua,proto3" json:"agua,omitempty"`
	Temperatura float64 `protobuf:"fixed64,14,opt,name=temperatura,proto3" json:"temperatura,omitempty"`
	// Altura do produto em milímetros.
	Nivel         float64 `protobuf:"fixed64,15,opt,name=nivel,proto3" json:"nivel,omitempty"`
	Origem        Origem  `protobuf:"varint,16,opt,name=origem,proto3,enum=medicao.Origem" json:"origem,omitempty"`
	Obs           string  `protobuf:"bytes,17,opt,name=obs,proto3" json:"obs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Medicao) Reset() {
	*x = Medicao{}
	mi := &file_apps_posto_medicao_medicao_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Medicao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Medicao) ProtoMessage() {}

func (x *Medicao) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_medicao_medicao_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Medicao.ProtoReflect.Descriptor instead.
func (*Medicao) Descriptor() ([]byte, []int) {
	return file_apps_posto_medicao_medicao_proto_rawDescGZIP(), []int{0}
}

func (x *Medicao) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Medicao) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Medicao) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Medicao) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Medicao) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Medicao) GetFields() *metadata.BasicFields {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Medicao) GetTanqueId() string {
	if x != nil {
		return x.TanqueId
	}
	return ""
}

func (x *Medicao) GetTanqueNumero() int32 {
	if x != nil {
		return x.TanqueNumero
	}
	return 0
}

func (x *Medicao) GetProdutoId() string {
	if x != nil {
		return x.ProdutoId
	}
	return ""
}

func (x *Medicao) GetProdutoNome() string {
	if x != nil {
		return x.ProdutoNome
	}
	return ""
}

func (x *Medicao) GetDataHora() *timestamppb.Timestamp {
	if x != nil {
		return x.DataHora
	}
	return nil
}

func (x *Medicao) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Medicao) GetAgua() float64 {
	if x != nil {
		return x.Agua
	}
	return 0
}

func (x *Medicao) GetTemperatura() float64 {
	if x != nil {
		return x.Temperatura
	}
	return 0
}

func (x *Medicao) GetNivel() float64 {
	if x != nil {
		return x.Nivel
	}
	return 0
}

func (x *Medicao) GetOrigem() Origem {
	if x != nil {
		return x.Origem
	}
	return Origem_ORIGEM_UNSPECIFIED
}

func (x *Medicao) GetObs() string {
	if x != nil {
		return x.Obs
	}
	return ""
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Medicao       *Medicao               `protobuf:"bytes,1,opt,name=medicao,proto3" json:"medicao,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_apps_posto_medicao_medicao_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_medicao_medicao_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_apps_posto_medicao_medicao_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequest) GetMedicao() *Medicao {
	if x != nil {
		return x.Medicao
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Medicao       *Medicao               `protobuf:"bytes,1,opt,name=medicao,proto3" json:"medicao,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_apps_posto_medicao_medicao_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_medicao_medicao_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_apps_posto_medicao_medicao_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResponse) GetMedicao() *Medicao {
	if x != nil {
		return x.Medicao
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Medicao       *Medicao               `protobuf:"bytes,2,opt,name=medicao,proto3" json:"medicao,omitempty"`
	UpdateMask    *metadata.FieldMask    `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_apps_posto_medicao_medicao_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_medicao_medicao_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_apps_posto_medicao_medicao_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRequest) GetMedicao() *Medicao {
	if x != nil {
		return x.Medicao
	}
	return nil
}

func (x *UpdateRequest) GetUpdateMask() *metadata.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Medicao       *Medicao               `protobuf:"bytes,1,opt,name=medicao,proto3" json:"medicao,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_apps_posto_medicao_medicao_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_medicao_medicao_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_apps_posto_medicao_medicao_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateResponse) GetMedicao() *Medicao {
	if x != nil {
		return x.Medicao
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hard          bool                   `protobuf:"varint,2,opt,name=hard,proto3" json:"hard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_apps_posto_medicao_medicao_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_medicao_medicao_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_apps_posto_medicao_medicao_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteRequest) GetHard() bool {
	if x != nil {
		return x.Hard
	}
	return false
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_apps_posto_medicao_medicao_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_medicao_medicao_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_apps_posto_medicao_medicao_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_apps_posto_medicao_medicao_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_medicao_medicao_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_apps_posto_medicao_medicao_proto_rawDescGZIP(), []int{7}
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Medicao       *Medicao               `protobuf:"bytes,1,opt,name=medicao,proto3" json:"medicao,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_apps_posto_medicao_medicao_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_medicao_medicao_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_apps_posto_medicao_medicao_proto_rawDescGZIP(), []int{8}
}

func (x *GetResponse) GetMedicao() *Medicao {
	if x != nil {
		return x.Medicao
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter        *filter.Filter         `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_apps_posto_medicao_medicao_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_medicao_medicao_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_apps_posto_medicao_medicao_proto_rawDescGZIP(), []int{9}
}

func (x *ListRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ListRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListRequest) GetFilter() *filter.Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MedicaoList   []*Medicao             `protobuf:"bytes,1,rep,name=medicao_list,json=medicaoList,proto3" json:"medicao_list,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_apps_posto_medicao_medicao_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_medicao_medicao_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_apps_posto_medicao_medicao_proto_rawDescGZIP(), []int{10}
}

func (x *ListResponse) GetMedicaoList() []*Medicao {
	if x != nil {
		return x.MedicaoList
	}
	return nil
}

func (x *ListResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type LeituraTanque struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TanqueNumero  int32                  `protobuf:"varint,1,opt,name=tanque_numero,json=tanqueNumero,proto3" json:"tanque_numero,omitempty"`
	Volume        float64                `protobuf:"fixed64,2,opt,name=volume,proto3" json:"volume,omitempty"`
	Agua          float64                `protobuf:"fixed64,3,opt,name=agua,proto3" json:"agua,omitempty"`
	Temperatura   float64                `protobuf:"fixed64,4,opt,name=temperatura,proto3" json:"temperatura,omitempty"`
	Nivel         float64                `protobuf:"fixed64,5,opt,name=nivel,proto3" json:"nivel,omitempty"`
	DataHora      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=data_hora,json=dataHora,proto3" json:"data_hora,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeituraTanque) Reset() {
	*x = LeituraTanque{}
	mi := &file_apps_posto_medicao_medicao_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeituraTanque) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeituraTanque) ProtoMessage() {}

func (x *LeituraTanque) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_medicao_medicao_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeituraTanque.ProtoReflect.Descriptor instead.
func (*LeituraTanque) Descriptor() ([]byte, []int) {
	return file_apps_posto_medicao_medicao_proto_rawDescGZIP(), []int{11}
}

func (x *LeituraTanque) GetTanqueNumero() int32 {
	if x != nil {
		return x.TanqueNumero
	}
	return 0
}

func (x *LeituraTanque) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *LeituraTanque) GetAgua() float64 {
	if x != nil {
		return x.Agua
	}
	return 0
}

func (x *LeituraTanque) GetTemperatura() float64 {
	if x != nil {
		return x.Temperatura
	}
	return 0
}

func (x *LeituraTanque) GetNivel() float64 {
	if x != nil {
		return x.Nivel
	}
	return 0
}

func (x *LeituraTanque) GetDataHora() *timestamppb.Timestamp {
	if x != nil {
		return x.DataHora
	}
	return nil
}

type RecebeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leituras      []*LeituraTanque       `protobuf:"bytes,1,rep,name=leituras,proto3" json:"leituras,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecebeRequest) Reset() {
	*x = RecebeRequest{}
	mi := &file_apps_posto_medicao_medicao_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecebeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecebeRequest) ProtoMessage() {}

func (x *RecebeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_medicao_medicao_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecebeRequest.ProtoReflect.Descriptor instead.
func (*RecebeRequest) Descriptor() ([]byte, []int) {
	return file_apps_posto_medicao_medicao_proto_rawDescGZIP(), []int{12}
}

func (x *RecebeRequest) GetLeituras() []*LeituraTanque {
	if x != nil {
		return x.Leituras
	}
	return nil
}

type RecebeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tanques do medidor sem cadastro no sistema.
	TanquesSemCadastro []int32 `protobuf:"varint,1,rep,packed,name=tanques_sem_cadastro,json=tanquesSemCadastro,proto3" json:"tanques_sem_cadastro,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RecebeResponse) Reset() {
	*x = RecebeResponse{}
	mi := &file_apps_posto_medicao_medicao_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecebeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecebeResponse) ProtoMessage() {}

func (x *RecebeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_posto_medicao_medicao_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecebeResponse.ProtoReflect.Descriptor instead.
func (*RecebeResponse) Descriptor() ([]byte, []int) {
	return file_apps_posto_medicao_medicao_proto_rawDescGZIP(), []int{13}
}

func (x *RecebeResponse) GetTanquesSemCadastro() []int32 {
	if x != nil {
		return x.TanquesSemCadastro
	}
	return nil
}

var File_apps_posto_medicao_medicao_proto protoreflect.FileDescriptor

const file_apps_posto_medicao_medicao_proto_rawDesc = "" +
	"\n" +
	" apps/posto/medicao/medicao.proto\x12\amedicao\x1a\x1cgoogle/api/annotations.proto\x1a\x1fplugins/validate/validate.proto\x1a\x1dplugins/service/service.proto\x1a\x13filter/filter.proto\x1a\x1ecommon/metadata/metadata.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdf\x04\n" +
	"\aMedicao\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x04 \x01(\tR\buserName\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\tR\x02id\x12-\n" +
	"\x06fields\x18\x06 \x01(\v2\x15.metadata.BasicFieldsR\x06fields\x12\x1b\n" +
	"\ttanque_id\x18\a \x01(\tR\btanqueId\x12#\n" +
	"\rtanque_numero\x18\b \x01(\x05R\ftanqueNumero\x12\x1d\n" +
	"\n" +
	"produto_id\x18\t \x01(\tR\tprodutoId\x12!\n" +
	"\fproduto_nome\x18\n" +
	" \x01(\tR\vprodutoNome\x127\n" +
	"\tdata_hora\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\bdataHora\x12\x16\n" +
	"\x06volume\x18\f \x01(\x01R\x06volume\x12\x12\n" +
	"\x04agua\x18\r \x01(\x01R\x04agua\x12 \n" +
	"\vtemperatura\x18\x0e \x01(\x01R\vtemperatura\x12\x14\n" +
	"\x05nivel\x18\x0f \x01(\x01R\x05nivel\x12'\n" +
	"\x06origem\x18\x10 \x01(\x0e2\x0f.medicao.OrigemR\x06origem\x12\x1a\n" +
	"\x03obs\x18\x11 \x01(\tB\b\xfaB\x05r\x03\x18\xf4\x03R\x03obs:\x03\xc0>\x01\";\n" +
	"\rCreateRequest\x12*\n" +
	"\amedicao\x18\x01 \x01(\v2\x10.medicao.MedicaoR\amedicao\"<\n" +
	"\x0eCreateResponse\x12*\n" +
	"\amedicao\x18\x01 \x01(\v2\x10.medicao.MedicaoR\amedicao\"\x81\x01\n" +
	"\rUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\amedicao\x18\x02 \x01(\v2\x10.medicao.MedicaoR\amedicao\x124\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x13.metadata.FieldMaskR\n" +
	"updateMask\"<\n" +
	"\x0eUpdateResponse\x12*\n" +
	"\amedicao\x18\x01 \x01(\v2\x10.medicao.MedicaoR\amedicao\"3\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04hard\x18\x02 \x01(\bR\x04hard\" \n" +
	"\x0eDeleteResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\vGetResponse\x12*\n" +
	"\amedicao\x18\x01 \x01(\v2\x10.medicao.MedicaoR\amedicao\"|\n" +
	"\vListRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x1f\n" +
	"\x06filter\x18\x05 \x01(\v2\a.FilterR\x06filter\"k\n" +
	"\fListResponse\x123\n" +
	"\fmedicao_list\x18\x01 \x03(\v2\x10.medicao.MedicaoR\vmedicaoList\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xd1\x01\n" +
	"\rLeituraTanque\x12#\n" +
	"\rtanque_numero\x18\x01 \x01(\x05R\ftanqueNumero\x12\x16\n" +
	"\x06volume\x18\x02 \x01(\x01R\x06volume\x12\x12\n" +
	"\x04agua\x18\x03 \x01(\x01R\x04agua\x12 \n" +
	"\vtemperatura\x18\x04 \x01(\x01R\vtemperatura\x12\x14\n" +
	"\x05nivel\x18\x05 \x01(\x01R\x05nivel\x127\n" +
	"\tdata_hora\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bdataHora\"C\n" +
	"\rRecebeRequest\x122\n" +
	"\bleituras\x18\x01 \x03(\v2\x16.medicao.LeituraTanqueR\bleituras\"B\n" +
	"\x0eRecebeResponse\x120\n" +
	"\x14tanques_sem_cadastro\x18\x01 \x03(\x05R\x12tanquesSemCadastro*J\n" +
	"\x06Origem\x12\x16\n" +
	"\x12ORIGEM_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rORIGEM_MANUAL\x10\x01\x12\x15\n" +
	"\x11ORIGEM_AUTOMATICA\x10\x022\xc1\x04\n" +
	"\x0eMedicaoService\x12`\n" +
	"\x06Create\x12\x16.medicao.CreateRequest\x1a\x17.medicao.CreateResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/posto/medicoes/create\x12`\n" +
	"\x06Update\x12\x16.medicao.UpdateRequest\x1a\x17.medicao.UpdateResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\x1a\x1a/api/posto/medicoes/update\x12[\n" +
	"\x06Delete\x12\x16.medicao.DeleteRequest\x1a\x17.medicao.DeleteResponse\" \x82\xd3\xe4\x93\x02\x1a*\x18/api/posto/medicoes/{id}\x12R\n" +
	"\x03Get\x12\x13.medicao.GetRequest\x1a\x14.medicao.GetResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/posto/medicoes/{id}\x12X\n" +
	"\x04List\x12\x14.medicao.ListRequest\x1a\x15.medicao.ListResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/posto/medicoes/list\x12`\n" +
	"\x06Recebe\x12\x16.medicao.RecebeRequest\x1a\x17.medicao.RecebeResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/posto/medicoes/recebeB\x8e\x01\n" +
	"\vcom.medicaoB\fMedicaoProtoP\x01Z5github.com/linksoft-dev/sdks/go/pb/apps/posto/medicao\xa2\x02\x03MXX\xaa\x02\aMedicao\xca\x02\aMedicao\xe2\x02\x13Medicao\\GPBMetadata\xea\x02\aMedicaob\x06proto3"

var (
	file_apps_posto_medicao_medicao_proto_rawDescOnce sync.Once
	file_apps_posto_medicao_medicao_proto_rawDescData []byte
)

func file_apps_posto_medicao_medicao_proto_rawDescGZIP() []byte {
	file_apps_posto_medicao_medicao_proto_rawDescOnce.Do(func() {
		file_apps_posto_medicao_medicao_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_posto_medicao_medicao_proto_rawDesc), len(file_apps_posto_medicao_medicao_proto_rawDesc)))
	})
	return file_apps_posto_medicao_medicao_proto_rawDescData
}

var file_apps_posto_medicao_medicao_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_apps_posto_medicao_medicao_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_apps_posto_medicao_medicao_proto_goTypes = []any{
	(Origem)(0),                   // 0: medicao.Origem
	(*Medicao)(nil),               // 1: medicao.Medicao
	(*CreateRequest)(nil),         // 2: medicao.CreateRequest
	(*CreateResponse)(nil),        // 3: medicao.CreateResponse
	(*UpdateRequest)(nil),         // 4: medicao.UpdateRequest
	(*UpdateResponse)(nil),        // 5: medicao.UpdateResponse
	(*DeleteRequest)(nil),         // 6: medicao.DeleteRequest
	(*DeleteResponse)(nil),        // 7: medicao.DeleteResponse
	(*GetRequest)(nil),            // 8: medicao.GetRequest
	(*GetResponse)(nil),           // 9: medicao.GetResponse
	(*ListRequest)(nil),           // 10: medicao.ListRequest
	(*ListResponse)(nil),          // 11: medicao.ListResponse
	(*LeituraTanque)(nil),         // 12: medicao.LeituraTanque
	(*RecebeRequest)(nil),         // 13: medicao.RecebeRequest
	(*RecebeResponse)(nil),        // 14: medicao.RecebeResponse
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
	(*metadata.BasicFields)(nil),  // 16: metadata.BasicFields
	(*metadata.FieldMask)(nil),    // 17: metadata.FieldMask
	(*filter.Filter)(nil),         // 18: Filter
}
var file_apps_posto_medicao_medicao_proto_depIdxs = []int32{
	15, // 0: medicao.Medicao.created_at:type_name -> google.protobuf.Timestamp
	15, // 1: medicao.Medicao.updated_at:type_name -> google.protobuf.Timestamp
	16, // 2: medicao.Medicao.fields:type_name -> metadata.BasicFields
	15, // 3: medicao.Medicao.data_hora:type_name -> google.protobuf.Timestamp
	0,  // 4: medicao.Medicao.origem:type_name -> medicao.Origem
	1,  // 5: medicao.CreateRequest.medicao:type_name -> medicao.Medicao
	1,  // 6: medicao.CreateResponse.medicao:type_name -> medicao.Medicao
	1,  // 7: medicao.UpdateRequest.medicao:type_name -> medicao.Medicao
	17, // 8: medicao.UpdateRequest.update_mask:type_name -> metadata.FieldMask
	1,  // 9: medicao.UpdateResponse.medicao:type_name -> medicao.Medicao
	1,  // 10: medicao.GetResponse.medicao:type_name -> medicao.Medicao
	18, // 11: medicao.ListRequest.filter:type_name -> Filter
	1,  // 12: medicao.ListResponse.medicao_list:type_name -> medicao.Medicao
	15, // 13: medicao.LeituraTanque.data_hora:type_name -> google.protobuf.Timestamp
	12, // 14: medicao.RecebeRequest.leituras:type_name -> medicao.LeituraTanque
	2,  // 15: medicao.MedicaoService.Create:input_type -> medicao.CreateRequest
	4,  // 16: medicao.MedicaoService.Update:input_type -> medicao.UpdateRequest
	6,  // 17: medicao.MedicaoService.Delete:input_type -> medicao.DeleteRequest
	8,  // 18: medicao.MedicaoService.Get:input_type -> medicao.GetRequest
	10, // 19: medicao.MedicaoService.List:input_type -> medicao.ListRequest
	13, // 20: medicao.MedicaoService.Recebe:input_type -> medicao.RecebeRequest
	3,  // 21: medicao.MedicaoService.Create:output_type -> medicao.CreateResponse
	5,  // 22: medicao.MedicaoService.Update:output_type -> medicao.UpdateResponse
	7,  // 23: medicao.MedicaoService.Delete:output_type -> medicao.DeleteResponse
	9,  // 24: medicao.MedicaoService.Get:output_type -> medicao.GetResponse
	11, // 25: medicao.MedicaoService.List:output_type -> medicao.ListResponse
	14, // 26: medicao.MedicaoService.Recebe:output_type -> medicao.RecebeResponse
	21, // [21:27] is the sub-list for method output_type
	15, // [15:21] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_apps_posto_medicao_medicao_proto_init() }
func file_apps_posto_medicao_medicao_proto_init() {
	if File_apps_posto_medicao_medicao_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_posto_medicao_medicao_proto_rawDesc), len(file_apps_posto_medicao_medicao_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_posto_medicao_medicao_proto_goTypes,
		DependencyIndexes: file_apps_posto_medicao_medicao_proto_depIdxs,
		EnumInfos:         file_apps_posto_medicao_medicao_proto_enumTypes,
		MessageInfos:      file_apps_posto_medicao_medicao_proto_msgTypes,
	}.Build()
	File_apps_posto_medicao_medicao_proto = out.File
	file_apps_posto_medicao_medicao_proto_goTypes = nil
	file_apps_posto_medicao_medicao_proto_depIdxs = nil
}
